include-dcc/include-portal-ui

src/App.tsx, src/auth/keycloak-api/index.ts, src/auth/keycloak-api/manager.ts, src/graphql/queries.ts, src/hooks/graphql/useGetExtendedMappings.ts, src/provider/ApolloProvider.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/index.tsx, src/views/DataExploration/index.tsx, src/views/Studies/index.tsx, src/views/Variants/index.tsx
Since apollo wasn't at the root, everytime a new page was called, a new apollo instance was created, invalidating the cache and re-do all the grapql request. Should be fix now
=> fix(apollo): should prevent inecessary request on route change

src/views/FileEntity/Title/index.module.scss, src/views/FileEntity/Title/index.tsx
- closes [SJIP-351](https://d3b.atlassian.net/browse/SJIP-351)
- Fix style to link to apply for data access
Before:
After:
=> fix: SJIP-351 Add underline to data access link

src/components/Icons/index.tsx, src/locales/en.ts, src/services/api/savedFilter/models.ts, src/services/api/savedSet/models.ts, src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/AddRemoveSaveSetModal.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx, src/views/DataExploration/utils/constant.ts
- close #[392](https://d3b.atlassian.net/browse/SJIP-392)
Descriptions
Goal: Add variants to saved sets and saved filters as it is done in KF-QA-Next. 
Saved Filters: Add a tab for Data Exploration and Variants. If a user saves a filter on the respective page, it will update the corresponding tab in the Saved Filters widget.
Saved Sets: Add Variants tab to the Saved Sets, if a user selects X variants in the Variants page, and saves them, it will save them in the set
=> fix(sets): SJIP-392 add savedsets and filters

src/components/Icons/ListAddIcon.tsx, src/components/Icons/ListRemoveIcon.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- close https://d3b.atlassian.net/browse/SJIP-345
Goal: Currently, we have the functionality of adding and removing saved sets across participants, biospecimen, and files. However, the icon illustrating these actions only represents a “participant” icon. We should replace this icon with a “list” icon that will be applied globally to the Participants, Biospecimen, Data files tab, and eventually for the variants page once we have the saved sets implemented. Ensure the icons matches the INCLUDE theme.
=> fix(sets): SJIP-345 change icons

src/views/VariantEntity/SummaryHeader/index.module.scss
- closes #[394](https://d3b.atlassian.net/browse/SJIP-394)
La couleur des mots (Study, Participants) devrait être gray-7
=> fix(variant): SJIP-394 fix text colors

src/views/DataExploration/components/TreeFacet/helpers.tsx
- closes #[352](https://d3b.atlassian.net/browse/SJIP-352)
Issue: Currently, the HPO/MONDO browsers do not seem to accept “/”. The search request becomes null as soon as a letter is added after inputting “/”. Aplasia/Hypoplasia of the breasts (HP:0010311) can be used an example. 
The Search input should be able to accept “/”. 
This error is seen across KF and INCLUDE
=> fix(hpobrowser): SJIP-352 allow / to be searched

src/views/Variants/components/GeneUploadIds/index.tsx
- closes #[398](https://d3b.atlassian.net/browse/SJIP-398)
Dans l’upload gene list de la page des variants, tenter de loader ce fichier ou copier/coller la liste de gènes.
https://user-images.githubusercontent.com/65532894/236477670-e13d7b07-c6c0-4115-b8c5-0e6e8f585322.mp4
=> fix(gene): SJIP-398 fix gene without alias

src/utils/translation.ts
- closes #[409](https://d3b.atlassian.net/browse/SJIP-409)
Issue: Use the term “Study Code” in the facet instead of “Study Id” similar to how it is in done in the query pill below.  We want to show the Study Codes that look like : DS-COG-ALL, DS-Sleep, ABC-DS, X01-Hakon, HTP, etc. . Not to be confused with the operational study codes that CHOP uses internally (SD____). These operational study codes should not be displayed as they mean nothing to the public
=> fix(facet): SJIP-409 change study id to study code

src/views/ProfileSettings/cards/Identification/index.tsx
- closes #[418](https://d3b.atlassian.net/browse/SJIP-418)
The Upload photo can be a potential security issue, therefore, until we figure out a more secure way of uploading a photo for the community page, we will remove the button.
=> fix(profil): SJIP-428 remove upload photo

package-lock.json, package.json, src/locales/en.ts, src/views/FileEntity/index.tsx, src/views/ParticipantEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/FileTable/index.tsx
- closes #[423](https://d3b.atlassian.net/browse/SJIP-423)
Similar to the Statistic buttons that are used to redirect to the Data Exploration, we will add a button “View in data exploration” on the right side of the table title for the respective entities. The filter to the Data Exploration page will be the same as the filters in the statistic button for the respective entity. 
Participant Entity tables:
Biospecimen (query = Participant ID, tab = Biospecimens)
Data File (query = Participant ID, tab = Data Files)
File Entity tables:
Participant / Sample  (query = File ID, tab = Participants)
@luclemo @kstonge
=> feat(entity): SJIP-423 add table extra and redirect link

src/graphql/participants/queries.ts, src/views/ParticipantEntity/utils/getPhenotypeColumns.tsx
#Condition Source Text should be the same for Phenotype and Diagnosis
- closes [SJIP-360](https://d3b.atlassian.net/browse/SJIP-360)
Phenotype source text should be the same a diagnosis source text
patient for testing : pt-4ijygj6gkk
...
@ QA, Design ...
=> fix: SJIP-360 condition source text same for phenotype and diagnosis

src/graphql/studies/models.ts, src/utils/string.ts, src/views/Community/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/ParticipantEntity/DiagnosisTable/MondoParticipantCount.tsx, src/views/ParticipantEntity/PhenotypeTable/HpoParticipantCount.tsx, src/views/Studies/index.tsx
[SJIP-397](https://d3b.atlassian.net/browse/SJIP-397)
Add comma as separator to thousand number.
Impacted pages:
- Dashboard => saved set number
- Studies table => column participants, biospecimen and families
- Community => member count
- Participant entity => diagnosis table MONDO shared term column, phenotype table HPO term column
=> fix(number): SJIP-397 add thousand separator

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/Studies/index.tsx, src/views/Variants/components/PageContent/VariantsTable/index.tsx
#[BUG] [Display dash in empty cell]
- closes [SJIP-407](https://d3b.atlassian.net/browse/SJIP-407)
Impacted pages : 
- Data exploration / participant tab : 
- (biospecimens 0 if no data)
- Data exploration / biospecimens tab : 
- participant
- collection ID
- laboratory procedure
- biospecimen storage
- (files 0 if no data)
- Data exploration / Data files tab : 
- data access
- file name
- data category
- access url
- format
- (particpants 0 if no data)
- (biospecimens 0 if no data)
- Studies
- Genomic
- transcriptomic
- proteomic
- Immun map
- metabolic
- Variant
- type
- frequencies
- homozygotes
=> fix(all): SJIP-407 add dash in empty cell

src/views/FileEntity/BiospecimenTable/index.tsx, src/views/FileEntity/index.tsx
- closes #[423](https://d3b.atlassian.net/browse/SJIP-423)
Le bouton devrait être sur la table Participant/Sample et non sur Data Type.
=> fix(file): SJIP-423 set the correct redirection to the correct table

src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes #[455](https://d3b.atlassian.net/browse/SJIP-455)
Issue: The tooltip for the “Sort” of a column only appears in the Data Files tab of the Data Exploration page. This was not implemented previously and seems to have automatically updated with FerlabUI ProTable. However, this tooltip only appears in the Data files tab and not the other two Participants, Biospecimens tables. Therefore, we will update the ProTable for the Participants and Biospecimens tab as well and any other ProTable used in the portal.
https://github.com/include-dcc/include-portal-ui/assets/65532894/d8a57f25-9226-4f3c-b277-d7b5f29ebc41
=> fix(file): SJIP-455 remove asc desc tooltip

src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
#[FEATURE] [Only display 1 experimental strategy for a file]
- ticket [SJIP-442](https://d3b.atlassian.net/browse/SJIP-442)
In data files tab from data exploration page, we want to see only one time each value.
=> feat(data exploration): SJIP-442 remove duplicate experimental strategy

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.module.scss, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.module.scss, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- closes [SJIP-446](https://d3b.atlassian.net/browse/SJIP-446)
Slightly widen the ID columns for Participant ID, Sample ID to ensure the IDs do not wrap.
=> style(dataExploration): SJIP-442 fix ID cell display

src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- closes [SPIJ-460](https://d3b.atlassian.net/browse/SJIP-460)
Add external participant ID column in the participant table form data exploration.
=> feat(paticipant): SJIP-460 add external id column

src/views/DataExploration/components/BiospecimenSearch.tsx, src/views/DataExploration/components/ParticipantSearch.tsx, src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx, src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx
- closes [SJIP-465](https://d3b.atlassian.net/browse/SJIP-465)
Since the data team changed how the IDs are represented in this data release, we will need to update the placeholders
- Search by Participant ID: e.g. pt-005X8BR9
- Search by Sample ID: e.g. bs-019260B4
- Search by Collection ID: e.g. bs-022KAEZW
- Upload participant list: e.g. pt-005X8BR9
- Upload sample list: e.g. bs-022KAEZW
=> feat(dataexplo): SJIP-465 update placeholders

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
- closes [SJIP-447](https://d3b.atlassian.net/browse/SJIP-447)
Add the Entity page redirect to the Participant ID in Biospecimen tab similar to the redirect for this field in the Participant tab
=> feat(data exploration): SJIP-447 add participant link in bio tab

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
- closes [SJIP-470](https://d3b.atlassian.net/browse/SJIP-470)
We will make container ID a default column placed in the Biospecimens Table of the Data Exploration page between Collection Sample Type and  Age (days).
=> feat(data exploration): SJIP-470 move default container ID column

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
- closes [SJIP-448](https://d3b.atlassian.net/browse/SJIP-448)
- Format age in biospecimen table
- Update column title
=> feat(data exploration): SJIP-448 format age in biospecimen table

src/graphql/participants/models.ts, src/services/api/reports/index.ts, src/views/DataExploration/utils/selectionSqon.ts, src/views/ParticipantEntity/AgeCell/index.tsx, src/views/ParticipantEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/DiagnosisTable/index.tsx, src/views/ParticipantEntity/PhenotypeTable/index.tsx, src/views/ParticipantEntity/utils/biospecimens.tsx, src/views/ParticipantEntity/utils/getDiagnosisColumns.tsx, src/views/ParticipantEntity/utils/getPhenotypeColumns.tsx
- closes #[435](https://d3b.atlassian.net/browse/SJIP-435)
The Download [Entity] buttons are not working. It seems like there is no call that is being made to Report API. The behaviour should be the same as what we see in PROD. The Data teams use the reports for QA purposes especially with the upcoming release.
=> fix(entity): SJIP-435 fix entity table download buttons

src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx, src/views/DataExploration/components/UploadIds/FileUploadIds.tsx, src/views/Variants/components/GeneUploadIds/index.tsx
- closes #308 
[SJIP-445](https://d3b.atlassian.net/browse/SJIP-445)
Impacted pages:
- data exploration: upload biospecimen ids
- data exploration: upload file ids
- variant: upload gene ids
=> fix(upload ids): SJIP-445 update pill display

package-lock.json, package.json, src/graphql/participants/actions.ts, src/graphql/participants/models.ts, src/graphql/participants/queries.ts, src/views/ParticipantEntity/FileTable/index.tsx, src/views/ParticipantEntity/utils/files.tsx
- closes [SJIP-471](https://d3b.atlassian.net/browse/SJIP-471)
In participant entity, category in file table doesn't display all data categories present in the app.
Fix progress bar display.
Same for exprimental strategy (not in the ticket but same place and behavior)
- Without file
- With file in each data category
- With file not in all data category
- Without file
- With file in each data category
- With file not in all data category
=> fix(participant entity): SJIP-471 display all data category in data files table

src/views/Dashboard/components/DashboardCards/SavedFilters/index.module.scss
- closes [SJIP-479](https://d3b.atlassian.net/browse/SJIP-479)
When we have lots of saved filters we need to scroll in the list.
=> fix(saved filters): SJIP-479 add scroll in widget

src/views/FileEntity/Title/index.tsx
- closes [SJIP-478](https://d3b.atlassian.net/browse/SJIP-478)
Remove manifest button in file entity page.
=> feat(file entity): SJIP-478 remove manifest button

src/views/ParticipantEntity/BiospecimenTable/index.tsx
- closes [SJIP-493](https://d3b.atlassian.net/browse/SJIP-493)
Fix menu tool in participant entity page for biospecimens table.
See attached video in ticket
=> fix(participant entity): SJIP-493 fix biospecimen menu tool

src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx
- closes [SJIP-488](https://d3b.atlassian.net/browse/SJIP-488)
Before we have only one icon for each type of set. According to the set type we want a different icon.
=> fix(saved set): SJIP-488 update icons

src/graphql/participants/models.ts, src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/ParticipantEntity/utils/summary.tsx
- closes [SJIP-482](https://d3b.atlassian.net/browse/SJIP-482)
It's missing the trio+ mapping into FamilyType to display the right label in the paticipant table.
=> fix(data exploration): SJIP-482 add trio+ family unit

src/locales/en.ts, src/locales/fr.ts, src/views/DataExploration/components/PageContent/index.module.scss, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/index.module.scss, src/views/DataExploration/index.tsx, src/views/Variants/components/PageContent/index.module.scss, src/views/Variants/components/PageContent/index.tsx, src/views/Variants/index.module.scss, src/views/Variants/index.tsx
- closes [SJIP-472](https://d3b.atlassian.net/browse/SJIP-472)
Add title of data exploration page. I have fixed too the style of the title in data exploration and variants pages.
=> feat(data exploration): SJIP-472 add title and fix style

src/views/ParticipantEntity/index.tsx, src/views/ParticipantEntity/utils/anchorLinks.tsx, src/views/ParticipantEntity/utils/summary.tsx
- closes [SJIP-497](https://d3b.atlassian.net/browse/SJIP-497)
Waiting a back end fix for family data, we need to : 
- mask family table
- mak the associated entry in the anchor menu
- add family id and a link to data exploration in the summary table
=> feat(participant): SJIP-497 mask family table and id in summary

src/App.tsx, src/graphql/constants.ts, src/graphql/variantsv2/actions.ts, src/graphql/variantsv2/models.ts, src/graphql/variantsv2/queries.ts, src/utils/routes.ts, src/views/DataExploration/components/SetsManagementDropdown/index.tsx, src/views/VariantEntityV2/SummaryHeader/index.module.scss, src/views/VariantEntityV2/SummaryHeader/index.tsx, src/views/VariantEntityV2/index.module.scss, src/views/VariantEntityV2/index.tsx, src/views/VariantEntityV2/utils/consequences.tsx, src/views/VariantEntityV2/utils/frequencies.tsx, src/views/VariantEntityV2/utils/pathogenicity.tsx, src/views/VariantEntityV2/utils/summary.tsx, src/views/VariantsV2/components/ConsequencesCell/consequences.ts, src/views/VariantsV2/components/ConsequencesCell/index.module.scss, src/views/VariantsV2/components/ConsequencesCell/index.tsx, src/views/VariantsV2/components/GeneUploadIds/index.module.scss, src/views/VariantsV2/components/GeneUploadIds/index.tsx, src/views/VariantsV2/components/PageContent/VariantsTable/index.module.scss, src/views/VariantsV2/components/PageContent/VariantsTable/index.tsx, src/views/VariantsV2/components/PageContent/index.module.scss, src/views/VariantsV2/components/PageContent/index.tsx, src/views/VariantsV2/components/VariantGeneSearch/OptionItem/index.module.scss, src/views/VariantsV2/components/VariantGeneSearch/OptionItem/index.tsx, src/views/VariantsV2/components/VariantGeneSearch/index.tsx, src/views/VariantsV2/index.module.scss, src/views/VariantsV2/index.tsx, src/views/VariantsV2/utils/constants.ts
WORK IN PROGRESS
adding stuff for new variants
Variant exploration page and variant entity page were duplicated in folders names were appended with `V2`. Same thing for queries.
exploration page for new variants can be accessed .../variants`_v2`/
=> :construction: Adding support for variants v2

src/views/DataExploration/utils/OntologyTree.tsx, src/views/DataExploration/utils/constant.ts
- closes # [SJIP-498](https://d3b.atlassian.net/browse/SJIP-498)
We have to remove other top roots as both the tree and sunburst cannot support them.  
...
=> fix: SJIP-498 eliminate unwanted mondo roots

src/style/themes/include/antd/tooltips.less
- closes [SJIP-499](https://d3b.atlassian.net/browse/SJIP-499)
Long tooltip go out of the box.
=> style(tooltip): SJIP-499 update white space

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/utils/selectionSqon.ts
- closes #[SJIP-475](https://d3b.atlassian.net/browse/SJIP-475)
The biospecimen download report in `Data Exploration` and `Particpant Entity page `have different fields they need to query on.
1. Data Exploration: Query on the keys ot the table, which corresponds to the ES id. (`sample_id` cannot be use as key as it would not be unique)
2. Participant Entity Page: we use the `sample_id` in this case (it is fine in this case)
See related issue: [SJIP-435](https://d3b.atlassian.net/browse/SJIP-435) for more history on this issue.
...
=> fix: SJIP-475 download biospecimen using _id and specimen_id

src/components/Layout/Header/index.tsx
- closes #[512](https://d3b.atlassian.net/browse/SJIP-512)
Set the Variant Exploration page with a toggle parameter. This will allow us to see what the page looks like while it is in PRD environment without letting the user access it.
=> feat(ft): SJIP-512 add feature toggle for variant

src/graphql/variants/models.ts, src/graphql/variants/queries.ts, src/locales/en.ts, src/utils/translation.ts, src/views/VariantEntity/FerlabComponent/EntityGeneConsequence.tsx, src/views/VariantEntity/FerlabComponent/EntityGeneConsequenceSubtitle.tsx
- closes [SJIP-502](https://d3b.atlassian.net/browse/SJIP-502)
Add fields in the consequence subtitle:
- biotype
- spliceAI ds
- gnomAD pLI
- gnomAD LOEUF
=> feat(explo variants): SJIP-502 add fields in subtilte consequence section

src/views/VariantEntity/FerlabComponent/EntityGeneConsequenceSubtitle.tsx
- closes #354 
[SJIP-502](https://d3b.atlassian.net/browse/SJIP-502)
Add colon after label in subtitle.
=> fix(variant): SJIP-502 add colon after label

src/views/Studies/index.tsx, src/views/Studies/utils/constants.ts
- closes #[526](https://d3b.atlassian.net/browse/SJIP-526)
add “first“ (set to 100 - arbitrary number) variable to the payload query in order to display all the studies
{"operationName":"getStudy","variables":{"sort":[{"field":"study_code","order":"asc"}]},"query":"query getStudy($sqon: JSON, $first: Int, $offset: Int, $sort: [Sort]) {\n study {\n hits(filters: $sqon, first: $first, offset: $offset, sort: $sort) {\n total\n edges {\n node {\n id\n study_id\n study_code\n study_name\n program\n external_id\n participant_count\n family_count\n biospecimen_count\n attribution\n data_category\n website\n }\n }\n }\n }\n}"}
=> fix(study): SJIP-526 improve max study size per query

src/views/FileEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/DiagnosisTable/index.tsx, src/views/ParticipantEntity/PhenotypeTable/index.tsx, src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[520](https://d3b.atlassian.net/browse/SJIP-520)
Participant Entity Page:
- Diagnosis Table
- Phenotype Tabe
- Biospecimen
(L'indexation étant en cours, il n'y avait pas de participant avec ces données)
File Entity Page:
- Participant / Sample table
=> fix(entity): SJIP-520 disable table export

package-lock.json, package.json, src/components/uiKit/FilterList/CustomFilterContainer.tsx, src/components/uiKit/FilterList/index.tsx, src/components/uiKit/FilterList/types.ts, src/graphql/utils/Filters.tsx, src/views/Variants/index.tsx
- closes [SJIP-521](https://d3b.atlassian.net/browse/SJIP-521)
Hide no data checbox on this facets:
- Variant > Position
- Gene > gnomAD pLI
- Gene > gnomAD LOEUF
- Pathogenicity > CADD 
- Pathogenicity > CADD (Phred)
- Pathogenicity > DANN 
- Pathogenicity > REVEL
- Pathogenicity >  SpliceAI
- Frequency > INCLUDE Allele Frequency
- Frequency > gnomAD Genome 2.1.1
- Frequency > gnomAD Genome 3
- Frequency > gnomAD Exome 2.1.1
- Frequency > TopMed
- Frequency > 1000 Genomes
=> feat(explo variants): SJIP-521 remove no data checkbox on range filter

src/graphql/biospecimens/models.ts, src/graphql/biospecimens/queries.ts, src/graphql/files/queries.ts, src/graphql/participants/queries.ts, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/index.tsx, src/views/VariantEntity/utils/frequencies.tsx
- closes [SJIP-508](https://d3b.atlassian.net/browse/SJIP-508)
- Add redirect to data explo on click on study code in frequency table (variant entity page)
- Use study code instead of study id in data explo for facet and in study coloumn in each tab (point 2, 3 and 4 in https://d3b.atlassian.net/browse/SJIP-527)
=> feat(variant): SJIP-508 add redirect on study code to data explo

src/components/Cavatica/AnalyzeModal/index.tsx, src/graphql/participants/queries.ts, src/views/FileEntity/utils/biospecimens.tsx, src/views/FileEntity/utils/getSummaryItems.tsx, src/views/ParticipantEntity/utils/summary.tsx, src/views/Studies/index.tsx, src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[527](https://d3b.atlassian.net/browse/SJIP-527)
Studies page – Study Code column
Participant Entity page
Summary section Study  (the study code is in parenthesis) 
Redirect Study
https://github.com/include-dcc/include-portal-ui/assets/65532894/bb48ace4-e17f-4009-9912-da78c1a5b0e1
File  Entity page
Summary section Study  (the study code is in parenthesis) 
Redirect Study
https://github.com/include-dcc/include-portal-ui/assets/65532894/53cb98b0-fa39-44f3-a022-4f32709e223b
Section Participnat/Sample, colonne Study
Analyze in Cavatica button modal
can only be tested on prod
=> fix(study): SJIP-527 change study_id to study_code

src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[532](https://d3b.atlassian.net/browse/SJIP-532)
When clicking on the study redirect, it seems like it doesn’t search the same study_code between variant and data exploration page as seen in the screenshots below. The Study Code should be the same between both pages. 
https://github.com/include-dcc/include-portal-ui/assets/65532894/fc603da8-09ad-4d0f-96cb-577b7221c4da
=> fix(variant): SJIP-532 fix study code

src/views/Variants/index.tsx
- closes [SJIP-530](https://d3b.atlassian.net/browse/SJIP-530)
Remove tooltip on GnomAD facets in variants.
=> feat(variants): SJIP-530 remove tooltip on gnomAD facets

src/views/ParticipantEntity/utils/biospecimens.tsx
- closes #[535](https://d3b.atlassian.net/browse/SJIP-535)
Set the Container ID as default in the Biopsecimen table of the part. entity page. We can see that there are many rows that seem identical but the actual unique values for certain studies is the container ID (or commonly known as aliquot). Place it after the Collection ID
=> feat(entity): SJIP-535 add container_id to biospecimen table

src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes [SJIP-537](https://d3b.atlassian.net/browse/SJIP-537)
In variant exploration page, add sort on this columns:
- gnomAD
- Studies
- Participant
- ALT
- Homozygote
=> feat(variants): SJIP-537 add sorters

src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #377 
[SJIP-537](https://d3b.atlassian.net/browse/SJIP-537)
- gnomAD 
- Studies **NOK** sort is not working with this kind of data
- Participant
- ALT
- Homozygote
- Frequency not required in this ticket but the sort was not working now it's OK
=> fix(variants): SJIP-537 fix key column to sort data

src/views/Dashboard/components/DashboardCards/AuthorizedStudies/ListItem/index.tsx, src/views/Studies/index.tsx
- closes [SJIP-541](https://d3b.atlassian.net/browse/SJIP-541)
- In dashboard, authorized studies redirec (I can't test because I don't have NIH credentials)
- In studies page, participant and biospecimen redirect
[Screencast from 07-04-23 14:57:54.webm](https://github.com/include-dcc/include-portal-ui/assets/133775440/5776d708-4e7f-4a61-954d-de749e7daa2f)
=> fix(studies): SJIP-541 study redirect

src/store/report/thunks.tsx, src/store/report/types.ts, src/views/FileEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/DiagnosisTable/index.tsx, src/views/ParticipantEntity/FamilyTable/index.tsx, src/views/ParticipantEntity/PhenotypeTable/index.tsx, src/views/ParticipantEntity/utils/family.tsx
- closes #[491)](https://d3b.atlassian.net/browse/SJIP-491)
Voir l’[analyse Notion](https://www.notion.so/ferlab/Participant-Entity-Page-91874cd663ac4cdb99ff709909169167?pvs=4#bbf1a0056c864b4297dc9a77970e2b8b) pour la nomenclature des fichiers générés des Export dans les pages Entity.
Ex. Le fichier généré pour la table Diagnosis devrait être include-diagnoses-table-2023-06-19
Vérifier tous les Export à partir des Page Entity.
=> fix(entity): SJIP-491 fix entity download file name

src/helpers/roles.ts, src/store/report/thunks.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/index.tsx, src/views/FileEntity/BiospecimenTable/index.tsx, src/views/FileEntity/utils/biospecimens.tsx, src/views/ParticipantEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/DiagnosisTable/index.tsx, src/views/ParticipantEntity/FamilyTable/index.tsx, src/views/ParticipantEntity/PhenotypeTable/index.tsx
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-538?atlOrigin=eyJpIjoiMTQ5ODI1NGZkMDNiNDljMDk3NzI0ZjI3ZjUxZTEwMTkiLCJwIjoiaiJ9)
NOTE: hpo terms is excluded from the tsv for phenotype table
=> :recycle: Refactor tsv to be performed client-side if needed

src/services/api/user/models.ts, src/views/Community/Member/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/ProfileSettings/cards/RoleAndAffiliation/index.tsx
1. Fix `Select All` for reports in Data-Exploration Page, Participants tab ([JIRA](https://d3b.atlassian.net/browse/SJIP-578?atlOrigin=eyJpIjoiZmUwOTFlNGRjMGRiNDQyYTg5ZjA3NzM4MjNlMTI3ZDUiLCJwIjoiaiJ9))
2. Fix Form in user settings, `Role & Affiliation` section ([JIRA](https://d3b.atlassian.net/browse/SJIP-586?atlOrigin=eyJpIjoiYzgwYTA2ZTJlODg2NDM0YTgzZTUwZmE3ZDBkODFhMTkiLCJwIjoiaiJ9))
=> Fix user profile and participant report select all

src/views/Community/index.tsx
- closes [#TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-603)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-603)
pagination for page one and two shows the same number.
https://github.com/include-dcc/include-portal-ui/assets/98903/48da392a-109b-46de-994e-8c44b3f7d95d
@kstonge
=> fix: SJIP-603 fix operator precedence for page navigation

src/views/Community/index.tsx
- closes [#603](https://d3b.atlassian.net/browse/SJIP-603)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-603)
Page index not correctly reset to 0 when a filter is activated
=> fix: SJIP-603 fix operator precedence for page navigation current page

package-lock.json, package.json, src/store/savedSet/thunks.ts, src/views/Dashboard/components/DashboardCards/BiospecimenRequests/ListItem.tsx
[SJIP-571](https://d3b.atlassian.net/browse/SJIP-571)
- on biospecimen request creation => add entry in dashboard widget
- on click on item from widget => redirection to data exploration with filter in a query
⚠️ we don't have the good result on the redirection du to an issue on field used to make the set and the data which is not unique for a sample id given.
Include also ferlab upgrade for style fixes. 
video is too big I put it in the ticket.
=> feat(bioreq): SJIP-571 redirect from widget

src/components/Biospecimens/Request/RequestBiospecimenModal.tsx, src/locales/en.ts
[SJIP-627](https://d3b.atlassian.net/browse/SJIP-627)
Change wording to manifest in modal message, button and in success message.
=> fix(bioreq): SJIP-627 change guideline to manifest

src/components/Biospecimens/Request/RequestBiospecimenButton.tsx, src/components/Biospecimens/Request/RequestBiospecimenModal.tsx, src/components/Biospecimens/Request/RequestBiospecimenTable.tsx, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
[SJIP-626](https://d3b.atlassian.net/browse/SJIP-626)
When we select all biospecimens in the table, the total count in the modal description need to be filled.
=> fix(bioreq): SJIP-626 select all count

src/locales/en.ts, src/middleware/AuthMiddleware.tsx, src/services/api/savedSet/index.ts, src/services/api/savedSet/models.ts, src/store/savedSet/slice.ts, src/store/savedSet/thunks.ts, src/store/savedSet/types.ts, src/views/Dashboard/components/DashboardCards/BiospecimenRequests/ListItem.tsx, src/views/Dashboard/components/DashboardCards/BiospecimenRequests/index.tsx
[SJIP-572](https://d3b.atlassian.net/browse/SJIP-572)
Add share feature in the dashboard widget to switch public the set and copy the link. For the receiver, be able to open the link to exploration page with the set of another person in his query builder.
N/A
Video is too big I will put it in the Jira ticket if you want to see it.
=> feat(biospecimen request): SJIP-572 add share feature

package-lock.json, package.json, src/locales/en.ts, src/store/savedFilter/thunks.ts, src/views/DataExploration/components/PageContent/index.tsx, src/views/Variants/components/PageContent/index.tsx
[SJIP-630](https://d3b.atlassian.net/browse/SJIP-630)
- Display the right error when you can't create a filter with an existing name filter
- Other fix, before if we have an error on update filter name in QB the name displayed is change even if is not save due to the error
Impact : 
- data exploration page
- variants page
- dashboard widget filter edition 
https://github.com/include-dcc/include-portal-ui/assets/133775440/0e3949da-98a6-477c-9c73-73b580ecd497
https://github.com/include-dcc/include-portal-ui/assets/133775440/de656784-36d2-4b75-bd91-7f0773323d96
=> fix(filter): SJIP-630 manage filter name

src/components/Biospecimens/Request/RequestBiospecimenButton.tsx, src/components/Biospecimens/Request/RequestBiospecimenLimitModal.tsx, src/components/Biospecimens/Request/RequestBiospecimenModal.tsx, src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
[SJIP-636](https://d3b.atlassian.net/browse/SJIP-636)
If the selection exceed 10 000, user can't download the manifest and a message is displayed to explain why.
=> feat(bioreq): SJIP-636 manage limit selection

src/views/VariantEntity/index.module.scss, src/views/VariantEntity/utils/frequencies.tsx
[SJIP-598](https://d3b.atlassian.net/browse/SJIP-598)
Align frequency participant link with value without link.
=> fix(variant): SJIP-598 align frequency part link

src/common/constants.ts, src/components/uiKit/reports/DownloadClinicalDataDropdown.tsx, src/components/uiKit/reports/DownloadFileManifestModal/FilesTable.tsx, src/components/uiKit/reports/DownloadFileManifestModal/index.module.scss, src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/components/uiKit/reports/DownloadRequestAccessModal/FilesTable.tsx, src/components/uiKit/reports/DownloadRequestAccessModal/index.module.scss, src/components/uiKit/reports/DownloadRequestAccessModal/index.tsx, src/components/uiKit/reports/TooMuchFilesAlert.tsx, src/locales/en.ts, src/services/api/reports/index.ts, src/services/api/reports/models.ts, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes #109
https://d3b.atlassian.net/browse/SJIP-109
Implement the Post-MVP version of File manifest button as it is done in KF but with the INCLUDE color scheme:
=> feat(file): SJIP-109 add file manifest download button

package-lock.json, package.json, src/components/uiKit/FilterList/GenericFilters.tsx, src/components/utils/filterUtils.tsx, src/graphql/utils/Filters.tsx, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/index.tsx, src/views/Variants/components/PageContent/index.tsx, src/views/Variants/index.tsx
[SJIP-612](https://d3b.atlassian.net/browse/SJIP-612)
Remove no data option for range filters in QB dropdown in Variants and Data exploration page.
=> fix(filter): SJIP-612 manage no data in QB

src/views/FileEntity/Title/index.tsx
- closes #[109](https://d3b.atlassian.net/browse/SJIP-109)
Il manque le bouton dans la page File Entity
@kstonge
=> fix(file): SJIP-109 add download manifest on page file entity

src/views/Dashboard/components/DashboardCards/BiospecimenRequests/index.tsx, src/views/Dashboard/components/DashboardCards/index.tsx, src/views/Dashboard/index.tsx
[SJIP-663](https://d3b.atlassian.net/browse/SJIP-663)
When variable environment for biospecimen request is toggled off we don't want an empty widget in the dashboard. We can see it on move other widget.
https://github.com/include-dcc/include-portal-ui/assets/133775440/e5537feb-a665-46a5-be83-2f5d2c59c55b
https://github.com/include-dcc/include-portal-ui/assets/133775440/05ed81b0-52cf-4046-8673-90b5e90f04e8
=> fix(bioreq): SJIP-663 fix ghost widget

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/SavedFilters/index.module.scss, src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.module.scss, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
Description
[SJIP-648](https://d3b.atlassian.net/browse/SJIP-648)
Rework empty tab for filter and set widget, change wording and style.
Rework style for list tab when we have no scroll to display fully height background
(Validate by Lucas)
=> feat(widget): SJIP-648 empty for filter and set

src/views/VariantEntity/SummaryHeader/index.tsx
[SJIP-638](https://d3b.atlassian.net/browse/SJIP-638)
When we are redirect to data exploration from variant entity by the studies link, the value filter generated produce a 500 error on value click to display the dropdown.
https://github.com/include-dcc/include-portal-ui/assets/133775440/e3573414-1349-4a52-8da7-5a61a883393f
https://github.com/include-dcc/include-portal-ui/assets/133775440/c8fcd53b-b36a-49cf-8843-14d75cb9bf18
=> fix(query): SJIP-638 fix redirect from variant

src/style/themes/include/antd/tags.less
[SJIP-688](https://d3b.atlassian.net/browse/SJIP-688)
- The link text color within tags should not change.
=> fix(tag): SJIP-688 link color in tag

src/components/Biospecimens/Request/NoSampleModal.tsx, src/components/Biospecimens/Request/RequestBiospecimenModal.tsx, src/components/Biospecimens/Request/requestBiospecimen.module.scss, src/style/themes/include/antd/alerts.less
[SJIP-649](https://d3b.atlassian.net/browse/SJIP-649)
the whole sentence shouldn’t be bolded. Only the authentication method and the  associated email or ID. This makes it so that the terms have an even heavier bold weight. See design and update accordingly.
In fact for biospecimen request I have added default style to bold alert title but when we don't have title the description is bold. So I change biospecimen request.
=> fix(profile): SJIP-649 alert message style

src/views/Variants/components/PageContent/VariantsTable/index.tsx
[SJIP-700](https://d3b.atlassian.net/browse/SJIP-700)
- display CADD phred instead of CADD raw in CADD column
=> fix(variants): SJIP-700 CADD value

src/store/user/slice.ts, src/store/user/thunks.ts
[SJIP-694](https://d3b.atlassian.net/browse/SJIP-694)
- When a user changes columns config he wants it's saved for an other visit.
See video in ticket.
https://github.com/include-dcc/include-portal-ui/assets/133775440/653f4461-237b-4b56-892f-fd93a12cc42a
=> fix(user): SJIP-694 user config lost

src/views/ProfileSettings/index.tsx
[SJIP-696](https://d3b.atlassian.net/browse/SJIP-696)
- Profile view from profile edition should not show a 404 error page before loading.
See video in ticket.
https://github.com/include-dcc/include-portal-ui/assets/133775440/770b6731-aa14-443f-a153-94179a6fd5ce
=> fix(profile): SJIP-696 remove 404 flash

src/views/VariantEntity/utils/summary.tsx
[SJIP-651](https://d3b.atlassian.net/browse/SJIP-651)
- Display dash when no data
=> fix(variant): SJIP-651 add dash when no data

src/components/Cavatica/AnalyzeButton/index.tsx, src/store/passport/thunks.ts, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes #[718](https://d3b.atlassian.net/browse/SJIP-718)
Lors du bulk import, il faudrait utiliser le même sorter que dans le tableau où on à fait selectAll quand on fetch les ids de fichiers. Car vue que plusieurs requêtes sont envoyé, on n’est pas sûr de recevoir les données dans le même ordre
=> feat(cavatica): SJIP-718 add sorter when starting cavatica analyse

src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx
[SJIP-728](https://d3b.atlassian.net/browse/SJIP-728)
- in `sm` and `md` grid size with default position, category graph must be on the right of demographic chart.
=> fix(summary): SJIP-728 fix default graph position

package-lock.json, package.json
[SJIP-712](https://d3b.atlassian.net/browse/SJIP-712)
- new Ferlab version which use StatisticIcon in DatasetEntity component
=> feat(study): SJIP-712 use new component StatisticIcon

src/locales/en.ts, src/views/VariantEntity2/index.tsx, src/views/VariantEntity2/utils/pathogenicity.tsx
[SJIP-738](https://d3b.atlassian.net/browse/SJIP-738)
- Add Pathogenicity section
-
=> feat(variant): SJIP-738 add pathogenicity section

package-lock.json, package.json, src/locales/en.ts, src/views/StudyEntity/index.tsx, src/views/StudyEntity/utils/summary.tsx
- closes #[711](https://d3b.atlassian.net/browse/SJIP-711)
Pourrais-tu mettre comme les titres des 2 charts
Most Frequent Phenotypes (HPO)
Most Frequent diagnoses (MONDO)
J’ai modifié le nom de la section à Statistic au lieu de “Data”  et le nom du tableau Pourra rester comme tu l’as “Summary Statistics”
Un peu de padding entre data access et le tableau de statistics
Faudrait que Clinical Data Source Type soit comma separated entre les valeurs
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-711)
=> fix(study): SJIP-711 adjust typo and styles

src/locales/en.ts, src/views/VariantEntity2/utils/summary.tsx
[SJIP-736](https://d3b.atlassian.net/browse/SJIP-736)
- Prediction label missing
- INCLUDE always in uppercase
=> fix(variant): SJIP-736 typos

src/graphql/summary/queries.ts, src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx
- closes #[749](https://d3b.atlassian.net/browse/SJIP-749)
Goal: 
Add a horizontal bar chart for the different Sample Types to summary view 
Title: Participants by Sample Type
X axis= “Sample Type” , each bar will represent a different Sample Type
Y axis = “# of participants”
Hover: Sample type:number of participants with X sample type
Include the Download data, SVG, PNG features like the other charts.
https://d3b.atlassian.net/browse/SJIP-749
=> feat(summary): SJIP-749 add participant by sample_type graph

package-lock.json, package.json, src/locales/en.ts, src/views/StudyEntity/index.tsx
- closes #[711](https://d3b.atlassian.net/browse/SJIP-711)
1. Le titre de l’axe des X pour les graphs HPO et MONDO n’est pas conforme à l’analyse
2. Les valeurs de l’axe des X ne devrait pas contenir « (HPO: 123056) » 
3. Mettre aux pluriels pour les axes des X, Phenotypes (HPO), Diagnoses (MONDO), Data Categories, Data Types
https://d3b.atlassian.net/browse/SJIP-711
=> fix(study): SJIP-711 fix typos

src/views/Studies/components/PageContent/index.tsx, src/views/Studies/index.tsx
- closes #[751](https://d3b.atlassian.net/browse/SJIP-751)
1. La liste des facettes et leurs titres ne sont pas conformes à l’analyse
Retire la facette domain, mais les titres doivent être changé du côté de l'api
2. Le key des lignes du tableau devrait être le Study Code (C'était comme ça avant). Ex. ici data-row-key="HTP"
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-751)
=> feat(study): SJIP-751 fix table row key

package-lock.json, package.json, src/components/reports/DownloadClinicalDataDropdown/index.tsx, src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/locales/en.ts, src/views/StudyEntity/SummaryHeader/index.module.scss, src/views/StudyEntity/SummaryHeader/index.tsx, src/views/StudyEntity/index.tsx
- closes #[771](https://d3b.atlassian.net/browse/SJIP-771)
- closes #[776](https://d3b.atlassian.net/browse/SJIP-776)
A study can be considered to have Harmonized or Unharmonized data. Typically if it is Harmonized, the study will be available to explore in the Data Exploration page. Otherwise, it shouldn’t be explorable in the Data Exploration page. Therefore, we will disable certain buttons in the Study entity page that would redirect to the Data Exploration or have certains actions based on data in the Data Exploration.
If study.is_harmonized=false have the following buttons in the study entity page disabled and add a tooltip when hovering over the buttons:
View in exploration button at the top of the page in the: 
Statistics Section
Files section
Summary section (Participant, …
=> feat(study): SJIP-776 SJIP-771 add exploration button, disabled when not harmonized

src/views/FileEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/FileTable/index.tsx
- closes #[778](https://d3b.atlassian.net/browse/SJIP-778)
We updated the design of the view in exploration button. See in figma design (recently done in Study). Update the design in the Participant Entity page – Biospecimen section and File entity page – Participant/sample section.
https://github.com/include-dcc/include-portal-ui/assets/65532894/d5c2d7c2-d602-4eb7-9309-62acfa1f31b4
https://github.com/include-dcc/include-portal-ui/assets/65532894/c833ae10-2d0d-424d-beae-9cd20b3f4692
=> feat(entity): SJIP-778 update view in data exploration design

src/store/passport/thunks.ts
- closes #[780](https://d3b.atlassian.net/browse/SJIP-780)
Despite being connected to the Auth Studies Fence and the Cavatica widget, the authorized unlock in the Data Files tab is displaying correctly, but when you attempt to analyze in Cavatica, it say the user does not have the authorization. This file should be authorized to move forward with the copy files to cavatica modal. 
For authorized Registered tier access files it seems like I can copy into Cavatica but for Controlled tier access files, i get this unauthorized modal.
=> fix(cavatica): SJIP-780 fix authorized files analyse

src/views/StudyEntity/index.tsx
- closes #[786](https://d3b.atlassian.net/browse/SJIP-786)
Goal: It seems like the Data Access section doesn’t appear for certain studies. They should be still displayed if there is a value in either one of the following fields. Currently the following have Study Contact information: DS-Nexus, DS-Sleep, BRi-DSR
Fields:
Access Limitation	
access_limitation in study.dataset
Access Requirement	
access_requirement in study.dataset
Study Contact	 
study.contact_name;
study.contact_email
=> fix(study): SJIP-786 fix data access display

src/locales/en.ts
- closes #[787](https://d3b.atlassian.net/browse/SJIP-787)
Goal: Update the Harmonized tag tooltip in the Summary Section and the Dataset Section
“Harmonized indicates that a subset of raw data provided by a study that has been normalized to the INCLUDE data model so that a valid comparison can be made across these studies. ”
[JIRA LINK]
=> fix(study): SJIP-787 fix typo

src/graphql/studies/queries.ts, src/locales/en.ts, src/utils/translation.ts, src/views/Studies/index.module.scss, src/views/Studies/index.tsx
[SJIP-765](https://d3b.atlassian.net/browse/SJIP-765)
Facets
- Add “Harmonized Data”
- Add Domain
Update the following to the notion spec:
- Part Lifespan Stages → Participant Lifespan Stage
- Study Designs → Design
Columns
- Add Data Access column
- Add Harmonized column
- Column header popover : “Harmonized Data”
- Add Domain column
Add User-defined columns (hidden in the column selection tool)
- Description
-Participant Lifespan
-Data Source
-Design
-Principal Investigator
-Start (with tooltip)
-End (with tooltip)
=> feat(studies): SJIP-765 update facets and columns

src/views/StudyEntity/utils/datasets.tsx
[SJIP-788](https://d3b.atlassian.net/browse/SJIP-788)
- add pmid link in dataset
=> feat(study): SJIP-788 add pmid link in dataset

src/views/Studies/index.module.scss, src/views/Studies/index.tsx
[SJIP-765](https://d3b.atlassian.net/browse/SJIP-765)
- remove safari tooltip
=> fix(studies): SJIP-765 remove safari tooltip

src/style/themes/include/_theme.template.scss, src/views/VariantEntity/index.module.scss, src/views/VariantEntity/index.tsx, src/views/VariantEntity/utils/summary.tsx
[SJIP-759](https://d3b.atlassian.net/browse/SJIP-759)
- Le souligné du gène devrait être de la même couleur que le texte
- Le tag devrait être gris comme les autres
- L’icône devrait être de la même couleur que celui pour Canonical
- Tous les tableaux ne devraient pas avoir les lignes alternés gris/blanc
=> fix(variant): SJIP-759 variant adjustments

src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/GraphContent/index.tsx
- closes #[802](https://d3b.atlassian.net/browse/SJIP-802)
It seems like the No data does not scale for certain charts (Participant by Data Category and Participants by sample type). It should be centered like the other charts. 
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-802)
=> fix(summary): SJIP-802 remove padding from no data message

package-lock.json, package.json, src/components/Cavatica/AnalyzeButton/index.tsx, src/services/analytics.ts, src/store/passport/thunks.ts, src/views/Dashboard/components/DashboardCards/Cavatica/index.tsx
- closes #[806](https://d3b.atlassian.net/browse/SJIP-806)
Add tag for when users click/create a project successfully either through the dashboard widget, analyze in Cavatica modal (Data Exploration/File entity)
Tag name: Cavatica project created
=> feat(cavatica): SJIP-806 add project creation analytics

src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx
- closes [#SJIP-815](https://d3b.atlassian.net/browse/SJIP-815)
=> fix: SJIP-815 enable svg download on studies chart

src/locales/en.ts, src/store/savedFilter/slice.ts, src/store/savedSet/slice.ts, src/store/savedSet/thunks.ts
- closes #[814](https://d3b.atlassian.net/browse/SJIP-814)
J’ai copié l’url d’un Biospecimen Requests à partir du widget.
J’ai supprimé ce Biospecimen Requests.
J’ai pasté l’url dans le browser.
J’ai cliqué sur l’onglet Dashboard.
Les Saved Sets et Biospecimen Requests sont en erreur.
[Peek 2024-04-22 10-54.webm](https://github.com/include-dcc/include-portal-ui/assets/65532894/5ac03880-06ba-4826-ad70-78ea6e69002d)
=> fix(biospecimen): SJIP-814 catch deleted biospecimen request url

src/locales/en.ts, src/store/savedFilter/slice.ts, src/store/savedFilter/thunks.ts, src/store/savedSet/thunks.ts
- closes #[814](https://d3b.atlassian.net/browse/SJIP-814)
Ça été fixé pour les Biospecimen Requests mais pas pour les Saved Filters.
[Peek 2024-04-23 08-16.webm](https://github.com/include-dcc/include-portal-ui/assets/65532894/d8d1bdd7-658c-4feb-9956-042c7a56e97f)
=> fix(savedfilter): SJIP-814 manage error when sharing saved filter

src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentDiagnosisGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentPhenotypesGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx
[SJIP-805](https://d3b.atlassian.net/browse/SJIP-805)
- Add Most Frequent Diagnoses/Phenotype graphs to the Summary View as it was done in the Study Entity page.
=> feat(dataexplo): SJIP-805 add graphs to summary

src/views/StudyEntity/index.tsx
- closes [#SJIP-803](https://d3b.atlassian.net/browse/SJIP-803)
=> fix: SJIP-803 add include prefix to charts and data download in Study Entity

src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.module.scss, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
[SJIP-829](https://d3b.atlassian.net/browse/SJIP-829)
- Display specific icon in authorization column for files controlled with DRS Cavatica
=> feat(files): SJIP-829 undetermined authorization

src/locales/en.ts, src/views/Login/TopBanner/MondoChart/index.tsx
- closes [#SJIP-838](https://d3b.atlassian.net/browse/SJIP-838)
Now:
=> fix: SJIP-838 adjust landing page mondo chart

src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-828)
Goal: Adjust Most Frequent Diagnoses/Phenotypes to be adjustable in size like the other graphs
Add drag icon to allow resizing of the graph with a click and drag action
set minimum sizing to ensure the graph can still be readable when reduced in size
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-828)
=> feat(grid): SJIP-828 make most frequent resizable

src/locales/en.ts, src/views/Studies/components/PageContent/NdaGuidsModal.tsx, src/views/Studies/components/PageContent/index.module.css, src/views/Studies/components/PageContent/index.tsx
Defect on [SJIP-1013](https://d3b.atlassian.net/browse/SJIP-1013)
- Add tooltip on guids button
- Redirect to studies page must be logged in
- Step icon is a check
https://github.com/user-attachments/assets/db718efb-8719-43e3-aa53-a32621753c96
=> fix(studies): SJIP-1013 fix icon, redirect and tooltip

src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1036)
To reduce the resources needed to load the Summary view page, we will remove the sunburst MONDO and HPO charts from the summary view
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1036)
=> fix(summary): SJIP-1036 remove mondo graph from summary

src/graphql/quickFilter/queries.ts, src/utils/translation.ts
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-983)
It seems like there are some fields missing to the Quick Filter. Add the following fields
Mutliselect type:
- Condition (Source Text)
- Vital Status
- Down Syndrome Status
- ACL
Range type:
- Age at Diagnosis (days)
- Age at Vital Status (days)
- Age at Observed Phenotype (days)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-983)
Condition (Source Text)
Vital Status
Down Syndrome Status
ACL
Age at Diagnosis (days)
Age at Vital Status (days)
Age at Observed Phenotype (days)
=> feat(quickfilter): SJIP-983 add missing quickfilter fields

src/views/DataExploration/utils/constant.ts
Add MONDO:0021178 in ignored root because it was under Human Disease before and now it's a "new" root. But it's not the root we want to take
=> feat: SKFP-905 ignore injury as root node

src/graphql/studies/queries.ts, src/views/Studies/index.module.css, src/views/Studies/index.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1032)
Studies can have more than one dbGaP code but in the studies table we only see one. If you go to the study entity page, we see more than one. Therefore, we will update the studies table to be able to have more than one value. If more than 1 value is present, display the “See more” option to display the other values. 
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1032)
=> feat(study): SJIP-1032 add multi external ids

src/components/uiKit/search/GlobalSearch/Search/index.tsx
[SJIP-1069](https://d3b.atlassian.net/browse/SJIP-1069)
- when the search text is empty we don't have suggestions
https://github.com/user-attachments/assets/1b21f83a-1cdd-45ef-a694-d5f5eea7ad41
https://github.com/user-attachments/assets/53aeffac-3d18-467b-9dba-db4e3ad8990d
=> fix(facet): SJIP-1069 search by empty options on close

src/components/uiKit/search/GlobalSearch/index.tsx
[SJIP-1068](https://d3b.atlassian.net/browse/SJIP-1068)
- Highlight auto complete suggestions with special character dash
https://github.com/user-attachments/assets/d8618116-b78e-43d5-96cb-fb98a079be64
https://github.com/user-attachments/assets/29778a20-4de3-4b50-905e-45153c1623e1
=> fix(facet): SJIP-1068 search by loses highlight

src/views/Community/components/Filters/Box/index.tsx, src/views/Community/index.tsx
[SJIP-1058](https://d3b.atlassian.net/browse/SJIP-1058)
- On another page than the first if I apply a filter I want to see the results
https://github.com/user-attachments/assets/717cccf9-fb25-428d-af36-83a74a8e8430
https://github.com/user-attachments/assets/94e27b1f-a2b9-4392-abe4-03f4f4fe3fce
=> fix(community): SJIP-1058 reset page index on select filter

src/views/Community/components/Filters/Box/index.tsx
[SJIP-1058](https://d3b.atlassian.net/browse/SJIP-1058)
- On another page than the first if I apply a filter I want to see the results
https://github.com/user-attachments/assets/47241c80-3715-4f52-9855-a920d3a728ac
https://github.com/user-attachments/assets/218691b9-0c27-4ade-bef3-1e38304122ab
=> fix(community): SJIP-1058 reset page on select usage filter

src/views/Analytics/Transcriptomic/Footer/index.tsx, src/views/Analytics/Transcriptomic/SwarmPlot/index.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1078)
Add Save biospecimen set button as it is done in the Data Exploration page
- opens the dropdown to create, add, remove biospecimens to a set
- If ≥ 10,000 in the selection, process the first 10k as it currently is already done in the Data Exploration page
- If no facets are applied, the saved set would represent all the samples used in the plot for that gene
- If facet is applied, the saved set would represent the resulting samples highlighted
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1078)
=> feat(transcriptomic): SJIP-1078 add saved set to biospecimen

src/locales/en.ts, src/views/Analytics/Transcriptomic/Heatmaps/index.tsx
- Closes SJIP-1051
Le tooltip devrait être:
```
Gene symbol: POFUT2
Fold change: 1.593246
q-value: 1.89e-19
```
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1051)
1. Go to transcriptomics
2. Select multiples genes
3. Hover on heatmap
=> fix(transcriptomics): SJIP-1051 fix typo

src/views/DataExploration/index.tsx, src/views/DataExploration/utils/quickFilter.tsx
- Closes SJIP-1093
Il semble que le compte affiché n’est pas celui des participants. L’icône dans le Quick Filter devrait donc refléter la bonne catégorie de données.
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1093)
=> fix(quickfilter): SJIP-1093 map icon to facet

src/App.tsx, src/components/Layout/Footer/index.tsx, src/components/PublicLayout/Header/HeaderButton/index.module.css, src/components/PublicLayout/Header/HeaderButton/index.tsx, src/components/PublicLayout/Header/index.module.css, src/components/PublicLayout/Header/index.tsx, src/components/PublicLayout/index.module.css, src/components/PublicLayout/index.tsx, src/utils/routes.ts, src/views/DataExploration/index.tsx, src/views/PublicStudies/index.tsx
- Closes SJIP-1118
Pour le Quick Filter, on ajoute bien l’icon Participant quand la valeur représente des participants, sinon non. Donc en effet si on match le nom d’une facet seulement je ne mettrais pas d’icon. Je peux ajouter cette précision dans la maquette ce matin.
Ensuite dans les facets il y auras bien différents icons suivant ce que représente la valeur (Participant, Biospecimen, Data file) 
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1118)
=> fix(quickfilter): SJIP-1118 fix first level icon

src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx
- Closes SJIP-1114
Across all horizontal bar charts set the max bars to 10. This is meant to improve visibility of the charts as it can become difficult to read the entries if there are too many bars. Generally, users will use these graphs to get a high level overview and not specifically look for those smaller bars. 
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1114)
=> fix(summary): SJIP-1114 only filter data in grid

src/common/downloader.ts, src/locales/en.ts, src/services/api/index.tsx, src/services/api/transcriptomics/index.ts, src/views/Analytics/Transcriptomic/Footer/DownloadTranscriptomics/index.tsx, src/views/Analytics/Transcriptomic/Footer/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- Closes SJIP-984
Add a download Data button for the volcano plot and the gene expression sample per gene plot. This will download the respective file in the S3 bucket. 
- [JIRA](https://d3b.atlassian.net/browse/SJIP-984)
=> feat(transcriptomics): SJIP-984 add download data buttons

src/views/Analytics/Transcriptomic/Footer/index.tsx, src/views/Analytics/Transcriptomic/index.tsx
- Closes SJIP-1124
Griser le bouton si le graphique Gene expression n’est pas affiché
https://github.com/user-attachments/assets/ded9d321-72d0-4aa5-891d-2bfc1aabe37a
=> fix(transcriptomics): SJIP-1124 disable download data when loading genes

src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
[SJIP-915](https://d3b.atlassian.net/browse/SJIP-915)
Center no data logo for Demographic graphs
- Center no data logo
=> fix(summary): SJIP-915 center no data in demographic graphs

src/locales/en.ts, src/views/Analytics/Transcriptomic/Footer/DownloadTranscriptomics/index.module.css, src/views/Analytics/Transcriptomic/Footer/DownloadTranscriptomics/index.tsx, src/views/Analytics/Transcriptomic/Footer/index.tsx
- Closes SJIP-1124
We can perhaps do Download gene expression data across all genes for the button under the boxplot.
If we think it would be to also have a tooltip for the download button under the volcano plot we can simply do Download differential gene expression across all genes
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1124)
=> fix(transcriptomics): SJIP-1124 add tooltip

src/components/PublicLayout/Header/index.tsx, src/components/PublicLayout/LoginModal/index.tsx, src/hooks/useQueryParams.tsx, src/views/PublicStudies/components/PageContent/index.tsx, src/views/PublicStudies/utils.tsx
[SJIP-1134](https://d3b.atlassian.net/browse/SJIP-1134)
Redirect to the correct page after modal login.
- Dashboard
- Data Exploration
- Variants
- Analysis
- Community
- Table study code => redirect to Studies page
- Table Participants column → redirect to Data Exploration Participant tab with
- Table files column → redirect to Data Exploration files tab
always redirect on studies page
https://github.com/user-attachments/assets/944c3429-3740-4008-a169-c48f9b67ff23
https://github.com/user-attachments/assets/77dbf810-a9f5-441c-8245-5861ff03dbdb
=> feat(studies): SJIP-1134 redirect after login on public page

src/store/analytics/slice.ts, src/views/Analytics/Transcriptomic/Heatmaps/index.tsx, src/views/Analytics/Transcriptomic/index.tsx
- Closes SJIP-1131
If user clicks on a gene, it will open the Sample Gene Expression Plot for that gene
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1131)
https://github.com/user-attachments/assets/ec5ef253-1852-4652-b1ff-5cf967443b50
=> feat(transcriptomic): SJIP-1131 add redirection to boxplot when clicking on heatmap element

src/graphql/participants/models.ts, src/graphql/participants/queries.ts, src/graphql/quickFilter/queries.ts, src/locales/en.ts, src/utils/translation.ts, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/index.tsx, src/views/ParticipantEntity/AgeCell/index.tsx, src/views/ParticipantEntity/utils/getProfileItems.tsx
[SJIP-1155](https://d3b.atlassian.net/browse/SJIP-1155)
Add age at first patient engagement
- Data exploration add facet (QF too), column and export
- Participant entity add in profile section
NA
=> feat(participant): SJIP-1155 add age at first patient engagement

src/components/Publication/NoPubMed.tsx
[SJIP-1162](https://d3b.atlassian.net/browse/SJIP-1162)
Remove copy icon on no pub med
- Remove copy icon on no pub med
=> fix(study): SJIP-1162 remove copy icon for no pub med

src/views/StudyEntity/utils/datasets.tsx
[SJIP-1000](https://d3b.atlassian.net/browse/SJIP-1000)
- Don't display empty fields
=> fix(study): SJIP-1000 dataset not display empty field

src/views/ParticipantEntity/AgeCell/index.tsx
[SJIP-1155](https://d3b.atlassian.net/browse/SJIP-1155)
no data must return only null value not 0
- manage 0 in age cell
=> fix(participant): SJIP-1155 manage 0 display for age

src/views/Analytics/Transcriptomic/ScatterPlot/index.tsx
[SJIP-1160](https://d3b.atlassian.net/browse/SJIP-1160)
Tooltip doesn't display the good value for fold change.
- Update fold change value in tooltip
=> fix(transcriptomic): SJIP-1160 update fold change value in tooltip

cypress/e2e/ManifestButton/Dataset.cy.ts, cypress/e2e/ManifestButton/PageDataExploration.cy.ts, cypress/e2e/ManifestButton/PageFile.cy.ts, src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/locales/en.ts, src/views/StudyEntity/index.tsx
[SJIP-1004](https://d3b.atlassian.net/browse/SJIP-1004)
Do not removed family checkbox in all pages, only in study entity.
Specify dataset in manifest filename.
- Conditional display of family checkbox, not for study page.
- add external id in manifest filename
Checkbox removed for all instances.
=> fix(study): SJIP-1004 manifest family checkbox removed only in study

cypress/e2e/Consultation/PageStudy.cy.ts, src/views/StudyEntity/utils/datasets.tsx
[SJIP-1179](https://d3b.atlassian.net/browse/SJIP-1179)
Dataset publication link not working
- Display data returned by back end
=> fix(study): SJIP-1179 fix publication link

src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Summary/CoOccuringConditions/index.module.css, src/views/DataExploration/components/PageContent/tabs/Summary/CoOccuringConditions/index.tsx
- Closes SJIP-1201
Add more spacing between columns and horizontal rows
Reduce the size of the axis label “# participants,” as it seems too large
Increase the text size of phenotypes at the row level by adjusting the ratio
Change the title to “Co-occurrence of Top 10 Conditions”
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1201)
=> feat(upset): SJIP-1201 adjust design

src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Summary/CoOccuringConditions/index.module.css, src/views/DataExploration/components/PageContent/tabs/Summary/CoOccuringConditions/index.tsx
- Closes SJIP-1228
Remove Hover Text Shifting:
Currently, the hover text over the vertical bars can be hidden if too close to the border of the summary view tile. As a simpler approach instead of trying to wrap the text or shift it left, we will remove this hover text displaying the intersections of the vertical bar
Adjust Histogram Labels:
Remove the HPO terms from the row text on the left histograms. However, we will retain the HPO terms on the tooltips across the diagram
Empty State when No Intersections:
Implement an empty state message when no intersections are found between phenotypes. (use PT_13QPZ5BQ)
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1228)
=> fix(upset): SJIP-1228 adjust theme

src/views/StudyEntity/index.tsx
[SJIP-1237](https://d3b.atlassian.net/browse/SJIP-1237)
The button for analyze in cavatica is no longer present in QA
Display cavatica button for dataset in DSC study entity
=> fix(study): SJIP-1237 update DSC dataset id for cavatica btn

package-lock.json, package.json, src/components/uiKit/search/SetSearch/index.tsx, src/locales/en.ts, src/store/venn/thunks.ts, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/index.tsx
- Closes SJIP-1243
1.**Goal**: Implement the following detailed modifications for the Venn diagram. 
After creating a set from the venn, redirect to the [entity] tab in the data exploration that was selected on the top right of the venn. I.e. if a user selected files on the top right of the venn and that is the count represented, after clicking “View set” it will redirect to the Data Files tab
2.**Issue**: Phantom sets should not appear in the saved set sidebar for all entities.
3.**Goal**: add logos based on entity types on the dropdown list. 
4.**Issue**: Update colour for logo disabled state colour, it should be the same as the text:
5.**Goal**: Currently, in order to save a name in the Venn for phantom sets, we need to provide a new name for the set despite never seeing the phantom …
=> fix(venn): SJIP-1243 add tab switching, icons and various bugsfix

src/views/StudyEntity/index.tsx, src/views/StudyEntity/utils/dataAccess.tsx
- Closes SJIP-1215
There are certain studies that don’t have data for many fields and it creates a rather empty table. Similar to what was done for the dataset section, hide the rows without values. 
Similarly, hide sections that don’t have data. This should technically already be implemented but it seems like the data access section is still present
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1215)
=> feat(study): SJIP-1215 update dataaccess display rules

package-lock.json, package.json, src/views/DataExploration/components/PageContent/index.tsx
- Closes SJIP-1257
When creating a venn with 2 queries, it caused a shifting of the display. Below are the two queries used. It doesn’t happen all the time but I opened it 5 times and the shifting occurred 2/5 times. 
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1257)
=> fix(venn): SJIP-1257 force static width and height for venn

src/graphql/summary/queries.ts, src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Summary/ParticipantsByAge/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx
- Closes SJIP-118
Goal: Add Vertical bar chart for Participants by Age at First Patient Engagement. A conversion of Age at First Patient Engagement from days to years  will be required. If a patient’s age is 12 years and 120 days, the patient would fall in the 12 years bracket in the group 10-19 ages for example.
Y-axis: # of participants
X-axis: Age at First Patient Engagement (years)
Age ranges will be in increments of 10. Eg. 0-9 , 10-19, 20-29…) 
mouseover tooltip on the bars: “Participants: number of participants"
Distinguish between controls and Trisomy 21 participants by having 2 bar pers age range with different colors. The controls and Trisomy 21 results can be found under the down syndrome status=t21 field.
Add a legend for the colour between controls and Trisomy 21. 
- …
=> feat(summary): SJIP-118 add participants by age graph

src/locales/en.ts
- Closes SJIP-1290
Missing parentheses for the counts after the X -axis variables. It should be T21 (304) and Control (96) in the X-axis labels and also seen in the legend. 
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1290)
=> fix(transcriptomic): SJIP-1290 add parenthesis for legend and x-axis

cypress/e2e/Consultation/PageVariant_1.cy.ts, src/locales/en.ts, src/views/VariantEntity/utils/consequence.tsx
[SJIP-731](https://d3b.atlassian.net/browse/SJIP-731)
Currently, we only have the picked symbol on the gene with the most deleterious consequence, but we should also have the symbol for the most deleterious consequence itself (the one that is the highlight at the top of the page). Place on the Consequence instead of the AA 
Add picked symbol on transcript
=> feat(variant): SJIP-731 add picked symbol on transcript

package-lock.json, package.json
- Closes SJIP-1334
Goal: Currently, the feature for the venn diagram is fairly hidden. A user needs to select 2-3 queries to be able to have the compare button appear. Therefore, we will always display the Compare button even when there is no selection for the queries. Place it betwene the label button and the new query button with the same styling that it currently has
When <2 queries selected:
Maintain the disable state
tooltip: Select 2 or 3 queries to generate a Venn diagram comparison
When >3 queries selected:
Maintain the disable state
tooltip: Only available with 2 or 3 queries selected
When 2 or 3 queries selected:
Active state as it currently is without a tooltip
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1334)
=> feat(querytool): SJIP-1334 always display compare button

src/components/Biospecimens/Tree/index.tsx, src/graphql/biospecimens/queries.ts, src/views/DataExploration/components/PageContent/tabs/Biospecimens/HierarchicalBiospecimenModal.tsx
[SJIP-1330](https://d3b.atlassian.net/browse/SJIP-1330)
Display sample infos on open.
- Open details table for sample clicked in biospecimen tab
https://github.com/user-attachments/assets/f5fc454b-0ef2-45a7-a709-b31c4fe713ff
=> fix(hierarchical): SJIP-1330 open sample clicked

package-lock.json, package.json, src/common/constants.ts, src/common/queryBuilder.ts, src/locales/en.ts, src/locales/es.ts, src/middleware/AuthMiddleware.tsx, src/services/api/savedSet/index.ts, src/services/api/savedSet/models.ts, src/store/savedSet/slice.ts, src/store/savedSet/thunks.ts, src/store/savedSet/types.ts, src/utils/translation.ts, src/views/Dashboard/components/DashboardCards/BiospecimenRequests/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/DataExploration/components/PageContent/index.tsx, src/views/Variants/components/PageContent/index.tsx
- Closes SJIP-1353
Add share link button to the saved sets widget across all entity types. A user will be able to copy the url for their saved set and share it with another user.
Unlike the biospecimen requests widget, instead of opening a warning modal, simply show the success message that the url was copied.
The query pill will be the corresponding entity type=saved set name (Participant, Biospecimen, File, Variant).
e.g. Participant = “This is my saved set name”, Variant = “This is my variant set”
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1353)
=> feat(set): SJIP-1353 add sharable saved sets

package-lock.json, package.json
[SJIP-1370](https://ferlab-crsj.atlassian.net/browse/SJIP-1370)
Race demographic chart is sliced in download png.
- See the legend
[SJIP-1370]: https://d3b.atlassian.net/browse/SJIP-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(study): SJIP-1370 increase demographic chart legend width

package-lock.json, package.json, src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Summary/CoOccuringConditions/index.tsx
[SJIP-1275](https://d3b.atlassian.net/browse/SJIP-1275)
Add the phenotype intersection to the QB
- Add icon info in card title
- Add vertical and horizontal onClick to add phenotypes to QB
No click and no info icon
https://github.com/user-attachments/assets/c63dec51-1a28-4726-a043-fe5db17a172e
[SJIP-1275]: https://d3b.atlassian.net/browse/SJIP-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(summary): SJIP-1275 add onclick on upset plot and info icon

src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentDiagnosisGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentPhenotypesGraphCard/index.tsx
[SJIP-1405](https://d3b.atlassian.net/browse/SJIP-1405)
Enrich Most Frequent Diagnosis graph tooltip.
- Add exact count and with descendant count.
[SJIP-1405]: https://d3b.atlassian.net/browse/SJIP-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(summary): SJIP-1405 improve tooltip of most frequent diagnosis graph

src/views/DataExploration/utils/quickFilter.tsx
[SJIP-1419](https://d3b.atlassian.net/browse/SJIP-1419)
Facet values already in query builder need to be checked too in quick filter first and second level.
- first level of QF need to be checked like QB values
https://github.com/user-attachments/assets/290826bb-a758-409d-b79a-f6c8a3a78820
https://github.com/user-attachments/assets/5e3cac6c-2238-4f95-aa82-4bc29432dd94
[SJIP-1419]: https://d3b.atlassian.net/browse/SJIP-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quickfilter): SJIP-1419 check first level of nested facet

src/graphql/participants/models.ts, src/graphql/participants/queries.ts, src/graphql/quickFilter/queries.ts, src/locales/en.ts, src/locales/es.ts, src/utils/translation.ts, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/index.tsx
- Closes SJIP-1440
Goal: Implemented the new field for the formatted version of the MAxO field that has the code + term. Currently, we only show the MAxO ID in the facet which makes it hard for the user to explore the MAxO terms as most people don’t have them memorized and would need to go to the MAxO website to know what the associated term is.
Therefore, like we do for the Diagnosis MONDO and the Phenotype HPO, and also how we display the MAxO term in the column of the table, we will create a formatted MAxO field in ES to be used with the facet
Formatted field: MAxO term (MAxO: MAxO ID)
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1440)
=> feat: SJIP-1440 Update intervention maxO
