src/graphql/files/models.ts
src/graphql/participants/queries.ts
src/views/DataExploration/components/PageContent/index.tsx
src/views/DataExploration/components/tabs/Participants/index.tsx

fix: JJIP:165 biospecimen counts and table ordering

---

src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/views/Studies/index.tsx

feat: #SJIP:213 add biospecimen count to study page

---

src/locales/en.ts
src/locales/fr.ts

closes [317](https://d3b.atlassian.net/browse/SJIP-317)

fix: SJIP-317 Data Files singular

---

src/views/DataExploration/components/SetsManagementDropdown/index.tsx

closes [295](https://d3b.atlassian.net/browse/SJIP-295)
Before:
After:

fix: SJIP-295 Disable dropdown when no items are selected

---

src/components/Layout/Header/index.module.scss

closes [321](https://d3b.atlassian.net/browse/SJIP-321)

fix: SJIP-321 Add focus state to header dropdown

---

src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx

closes [316](https://d3b.atlassian.net/browse/SJIP-316)

fix: SJIP-316 Rename Study Code column

---

src/App.tsx
src/graphql/files/actions.ts
src/graphql/files/models.ts
src/graphql/files/queries.ts
src/locales/en.ts
src/services/api/user/models.ts
src/utils/routes.ts
src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
src/views/FileEntity/BiospecimenTable/index.tsx
src/views/FileEntity/SummaryHeader/index.module.scss
src/views/FileEntity/SummaryHeader/index.tsx
src/views/FileEntity/Title/index.module.scss
src/views/FileEntity/Title/index.tsx
src/views/FileEntity/index.tsx
src/views/FileEntity/utils/anchorLinks.tsx
src/views/FileEntity/utils/getBiospecimensColumns.tsx
src/views/FileEntity/utils/getDataAccessItems.tsx
src/views/FileEntity/utils/getDataTypeItems.tsx
src/views/FileEntity/utils/getSummaryItems.tsx
src/views/Variants/components/PageContent/index.tsx

- closes [SJIP-351](https://d3b.atlassian.net/browse/SJIP-351)
First version of the File Entity Page.
After:

feat: SJIP-351 File Entity page

---

src/components/Biospecimens/DownloadDataButton/index.tsx
src/graphql/biospecimens/models.ts
src/graphql/participants/queries.ts
src/locales/en.ts
src/utils/dates.ts
src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
src/views/FileEntity/SummaryHeader/index.module.scss
src/views/FileEntity/SummaryHeader/index.tsx
src/views/ParticipantEntity/AgeCell/index.module.scss
src/views/ParticipantEntity/AgeCell/index.tsx
src/views/ParticipantEntity/BiospecimenTable/index.tsx
src/views/ParticipantEntity/SummaryHeader/index.module.scss
src/views/ParticipantEntity/SummaryHeader/index.tsx
src/views/ParticipantEntity/utils/biospecimens.tsx
src/views/ParticipantEntity/utils/getDiagnosisColumns.tsx
src/views/ParticipantEntity/utils/getPhenotypeColumns.tsx
src/views/ParticipantEntity/utils/summary.tsx

- closes [SJIP-350](https://d3b.atlassian.net/browse/SJIP-350)
- Extracted DownloadDataButton in its own component for reuse in participant entity page
- Created AgeCell to handle age formatting in tables
- Adjusted styles and labels where needed

feat: SJIP-350 Adjustments to participant entity page

---

package.json
src/graphql/files/queries.ts
src/locales/en.ts
src/views/FileEntity/SummaryHeader/index.module.scss
src/views/FileEntity/SummaryHeader/index.tsx
src/views/FileEntity/Title/index.tsx
src/views/FileEntity/index.module.scss
src/views/FileEntity/utils/biospecimens.tsx
src/views/FileEntity/utils/getDataAccessItems.tsx
src/views/FileEntity/utils/getSummaryItems.tsx

- closes [SJIP-351](https://d3b.atlassian.net/browse/SJIP-351)
- Multiple minor adjustment to the file entity page
- Deployment will fail until ferlab [PR](https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/221) is merged

fix: SJIP-350 Adjustments to file entity page

---

src/App.tsx
src/locales/en.ts
src/utils/routes.ts
src/utils/translation.ts
src/views/VariantEntity/SummaryHeader/index.module.scss
src/views/VariantEntity/SummaryHeader/index.tsx
src/views/VariantEntity/index.module.scss
src/views/VariantEntity/index.tsx
src/views/VariantEntity/utils/consequences.tsx
src/views/VariantEntity/utils/frequencies.tsx
src/views/VariantEntity/utils/pathogenicity.tsx
src/views/VariantEntity/utils/summary.tsx

- closes [SJIP-377](https://d3b.atlassian.net/browse/SJIP-377)
- Implement Variant entity page 
After:

feat: SJIP-377 Variant entity page

---

package-lock.json
package.json
src/graphql/utils/Filters.tsx
src/graphql/utils/nameTransformer.tsx
src/utils/translation.ts

Description
There isn’t supposed to be a TRUE value under the chromosome facet. This was a known issue when developing the UCSF portal and it was noted to be related to the UI kit on the front-end. It corresponds to the Chromosome 1. Filtering for this field shows a table for 0 results.

fix(facet): SJIP-389 fix true value for chromosome 1

---

src/views/Variants/components/PageContent/index.tsx

https://user-images.githubusercontent.com/65532894/234974188-ea131b36-0bfa-4f75-ae39-7fc3461950f1.mp4

fix(variant): fix search after

---

src/locales/en.ts
src/views/VariantEntity/SummaryHeader/index.tsx

:bug: Fix participant count display and redirect in var entity page

---

package-lock.json
package.json
src/graphql/queries.ts
src/graphql/utils/Filters.tsx
src/graphql/utils/nameTransformer.tsx

Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/274

fix(filter): SJIP-389 use key_as_string instead of key for boolean

---

src/graphql/biospecimens/actions.ts
src/graphql/biospecimens/queries.ts
src/graphql/files/actions.ts
src/graphql/files/queries.ts
src/graphql/participants/actions.ts
src/graphql/participants/queries.ts
src/utils/helper.ts
src/views/DataExploration/components/PageContent/index.tsx
src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
src/views/DataExploration/utils/constant.ts

Ajout du search after dans data-exploration
https://user-images.githubusercontent.com/65532894/235163778-e95d747d-800c-4d30-b7ee-8e3b080e03f7.mp4
https://user-images.githubusercontent.com/65532894/235163790-e868a0fe-92d5-4c78-a988-a94ed5987842.mp4
https://user-images.githubusercontent.com/65532894/235163795-dc51b9cf-e7b3-44e7-bdfd-0efac253531a.mp4

feat(exploration): SJIP-378 add search after on all tab

---

src/views/VariantEntity/SummaryHeader/index.module.scss

fix(entity): SJIP-394 fix colors

---

src/views/ParticipantEntity/utils/dataCategory.tsx
src/views/ParticipantEntity/utils/experimentalStrategy.tsx

fix(entity): SJIP-363 add tooltips on file table

---

src/views/DataExploration/components/TreeFacet/index.module.scss

fix(hpo): SJIP-294 fix overflow

---

src/views/Studies/index.tsx

Goal: Add dashes to empty cells as it is done in the Data Exploration page.

fix(study): SJIP-348 fix empty external id

---

src/locales/en.ts
src/views/FileEntity/Title/index.module.scss
src/views/FileEntity/Title/index.tsx

close https://d3b.atlassian.net/browse/SJIP-376

fix(file): SKIP-376 change tooltip to popover

---

src/store/savedSet/index.ts
src/views/Dashboard/components/DashboardCards/SavedFilters/index.module.scss

- closes #[404](https://d3b.atlassian.net/browse/SJIP-404)
Les cartes sont mal alignées dans la dashboard
...
@ QA, Design ...

fix(dashboard): SJIP-404 fix card padding

---

src/components/uiKit/charts/Bar/index.module.scss
src/services/api/user/models.ts
src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/index.module.scss
src/views/DataExploration/components/PageContent/tabs/Summary/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx

- closes #[400](https://d3b.atlassian.net/browse/SJIP-400)
Ajouter le nouveau système de grille au Summary View

feat(summary): SJIP-400 add new summary

---

src/locales/en.ts
src/views/FileEntity/Title/index.tsx

- closes #[376](https://d3b.atlassian.net/browse/SJIP-376)
Il manque le titre et un point à la fin.

fix(file): SJIP-376 fix popover title

---

package-lock.json
package.json

- closes #[413](https://d3b.atlassian.net/browse/SJIP-413)
Add missing spinner (fixed ferlab side)

fix(table): SJIP-413 add missing spinner

---

src/graphql/studies/actions.ts
src/graphql/studies/queries.ts
src/locales/en.json
src/utils/translation.ts
src/views/Studies/index.tsx

- closes #[422](https://d3b.atlassian.net/browse/SJIP-422)
- closes #[421](https://d3b.atlassian.net/browse/SJIP-421)
- closes #[420](https://d3b.atlassian.net/browse/SJIP-420)
Goal: Change "Family Type" Facet name to "Family Unit" to match the column
Goal:  Change "Observed Phenotype (HPO)" to "Phenotype (HPO) in facet
Sort the Studies Alphabetically based on the Study code

fix(facet): SJIP-420 SJIP-421 SJIP-422 fix typo and studies sorting

---

src/utils/translation.ts

- closes #[416](https://d3b.atlassian.net/browse/SJIP-416)
In QA, Adjust Status facet for Availability under Biospecimen Category as it is done in PRD.

fix(facet): SJIP-416 change status to availability

---

src/views/DataExploration/components/TreeFacet/TreeFacetModal.tsx

- closes #[402](https://d3b.atlassian.net/browse/SJIP-402)
Fix character limit search

fix(hpo): SJIP-402 fix search limit

---

.github/CODEOWNERS
.github/pull_request_template.md

Add PR template and codeowners

fix: FLUI-63 pr template and codeowners

---

package-lock.json
package.json
src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx

- closes #303 
[SJIP-397](https://d3b.atlassian.net/browse/SJIP-397)
Fix QA comment to format items count with thousand separator.

fix(itemscount): SJIP-397 update ferlab UI version

---

src/components/Cavatica/AnalyzeModal/index.tsx
src/components/Cavatica/CreateProjectModal/index.tsx
src/views/Dashboard/components/DashboardCards/SavedFilters/EditModal/index.tsx
src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx
src/views/DataExploration/components/SetsManagementDropdown/AddRemoveSaveSetModal.tsx
src/views/DataExploration/components/TreeFacet/TreeFacetModal.tsx
src/views/DataExploration/components/TreeFacet/helpers.tsx
src/views/ProfileSettings/cards/Identification/ProfileImageUpload.tsx

- closes [SJIP-382](https://d3b.atlassian.net/browse/SJIP-382)
HPO or MONDO search with a dash value is not working. I don't find any other special charcter in HPO or MONDO name.

fix(HPO/MONDO): SJIP-382 search by - value

---

src/style/themes/include/antd/tooltips.less
src/views/FileEntity/utils/biospecimens.tsx

- closes [SJIP-449](https://d3b.atlassian.net/browse/SJIP-449)
Fix tool menu display for the third element in the list of particpant / sample table.

fix(fileEntity): SJIP-449 fix tool menu in participant / sample

---

src/views/Studies/index.tsx
src/views/Studies/utils/constant.ts

- closes [SJIP-480](https://d3b.atlassian.net/browse/SJIP-480)
Some study links are not working because don't have a website value.

fix(studies): SJIP-480 fix study id link

---

src/locales/en.ts

- closes [SJIP-486](https://d3b.atlassian.net/browse/SJIP-486)
Update query pill translation to have id in uppercase and remove sample in 'collection sample id'.

fix(data exploration): SJIP-486 update pill label translation

---

src/views/Community/components/Filters/Box/index.tsx

- closes [SJIP-494](https://d3b.atlassian.net/browse/SJIP-494)
In community page, clear button in input filter is not working.
See video in the ticket
[Screencast from 06-21-23 14:15:02.webm](https://github.com/include-dcc/include-portal-ui/assets/133775440/8f8decad-f182-4120-b28c-226ddae6ea3f)

fix(community): SJIP-494 clear filter

---

src/graphql/variantsv2/actions.ts
src/graphql/variantsv2/models.ts
src/views/VariantEntityV2/FerlabComponent/Consequences.utils.tsx
src/views/VariantEntityV2/FerlabComponent/EntityGeneConsequence.tsx
src/views/VariantEntityV2/FerlabComponent/EntityGeneConsequenceSubtitle.tsx
src/views/VariantEntityV2/SummaryHeader/index.tsx
src/views/VariantEntityV2/index.tsx
src/views/VariantEntityV2/utils/consequences.tsx
src/views/VariantEntityV2/utils/summary.tsx

Entity variant V2, update : 
- Entity title
- Entity summary
- Gene consequence

feat(variant entity V2): update entity title, summary and gene consequence tables

---

src/utils/translation.ts
src/views/VariantsV2/components/PageContent/VariantsTable/index.tsx
src/views/VariantsV2/index.tsx

:pencil: Add labels to facets - variants v2

---

src/utils/translation.ts
src/views/VariantsV2/index.tsx

:pencil: Add new facets variants 2

---

src/views/VariantsV2/index.tsx

:speech_balloon: Change facets order

---

src/graphql/variantsv2/actions.ts
src/utils/translation.ts
src/views/VariantEntityV2/index.tsx
src/views/VariantEntityV2/utils/frequencies.tsx
src/views/VariantsV2/index.tsx

:bug: Fix freq in v entity 2 and add cadd_pred to facets in v 2

---

src/store/report/thunks.tsx
src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
src/views/Dashboard/components/DashboardCards/index.tsx
src/views/VariantEntity/FerlabComponent/Consequences.utils.tsx
src/views/VariantEntity/FerlabComponent/EntityGeneConsequence.tsx
src/views/VariantEntity/FerlabComponent/EntityGeneConsequenceSubtitle.tsx
src/views/VariantEntity/FerlabComponent/EntityPublicCohortTable.tsx
src/views/VariantEntity/FerlabComponent/EntityPublicCohortTable.utils.tsx
src/views/VariantEntity/FerlabComponent/Pathogenecity.utils.tsx
src/views/VariantEntity/SummaryHeader/index.tsx
src/views/VariantEntity/index.tsx
src/views/VariantEntity/utils/frequencies.tsx
src/views/VariantEntity/utils/summary.tsx
src/views/Variants/components/ConsequencesCell/index.tsx
src/views/Variants/components/PageContent/VariantsTable/index.tsx

- closes [SJIP-507](https://d3b.atlassian.net/browse/SJIP-507)
I have commented the code to save a variant set and the list in the dashboard because there are some bugs for deployment.

feat(variant): SJIP-507 mask save set

---

src/App.tsx
src/locales/en.ts

- closes #[519](https://d3b.atlassian.net/browse/SJIP-519)
Add a maintenance page
use REACT_APP_MAINTENANCE_MODE=true flag

feat(app): SJIP-512 add a maintenance page

---

src/graphql/biospecimens/queries.ts
src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx

- closes #[SJIP-469](https://d3b.atlassian.net/browse/SJIP-469)
Add external_sample_id to biospecimen table
N/A
...

fix: SJIP-469 add external sample id to table

---

NEWS.md
package-lock.json
package.json

feat: SJIP-503 release 1 7 0

---

src/views/DataExploration/index.tsx

- closes #362 
Data Exploration
Biospecimen > Age at biospecimen Collection

feat(dataexplo): SJIP-521 hide no data for age

---

src/store/fenceStudies/thunks.ts

fix: SJIP-529 auth studies sqon fix

---

NEWS.md
package-lock.json
package.json

Release 1 7 1

---

src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
src/views/FileEntity/BiospecimenTable/index.tsx
src/views/ParticipantEntity/BiospecimenTable/index.tsx
src/views/ParticipantEntity/DiagnosisTable/index.tsx
src/views/ParticipantEntity/PhenotypeTable/index.tsx
src/views/ParticipantEntity/index.tsx
src/views/ParticipantEntity/utils/anchorLinks.tsx
src/views/Variants/components/PageContent/VariantsTable/index.tsx

chore(project): SJIP-000 re-add commented code for webinar

---

package-lock.json
package.json

- closes [SJIP-511](https://d3b.atlassian.net/browse/SJIP-511)
We want the highlight of the menu follow the scroll in the page.

feat(anchor menu): SJIP-511 upgrade ferlab

---

src/locales/en.ts
src/locales/fr.ts

- closes #[381](https://d3b.atlassian.net/browse/SJIP-381)
Fix typos

fix(member): SJIP-381 fix typos

---

src/locales/en.ts

- closes #[539](https://d3b.atlassian.net/browse/SJIP-539)
L’item « Download data » devrait être Sentence case

fix(summary): SJIP-539 fix typos

---

src/style/themes/include/antd/tables.less

- closes #[379](https://d3b.atlassian.net/browse/SJIP-379)
Table header (sort = true) hover state
Row cell hover state
Row cell selected hover state (celle du bas est en hover vue qu'on ne voit pas mon cursor de souris dans la capture)
Row control checked false hover
Row control checked true hover
...
@kstonge

fix(table): SJIP-379 adjust colors

---

src/views/ParticipantEntity/utils/summary.tsx

:pencil: Remove family Id from summary in participant entity page

---

src/views/FileEntity/BiospecimenTable/index.tsx
src/views/ParticipantEntity/BiospecimenTable/index.tsx
src/views/ParticipantEntity/DiagnosisTable/index.tsx
src/views/ParticipantEntity/PhenotypeTable/index.tsx
src/views/ParticipantEntity/utils/biospecimens.tsx
src/views/ParticipantEntity/utils/getDiagnosisColumns.tsx

https://d3b.atlassian.net/browse/SJIP-557

:bug: Fix tsvS in participant entity page and file entity page

---

src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx

[SJIP-547](https://d3b.atlassian.net/browse/SJIP-547)
Les données des graphiques 'Demographic' sont interverties entre sexe et race.

fix(summary): SJIP-547 fix data

---

src/store/fenceStudies/thunks.ts
src/store/fenceStudies/types.ts
src/views/Dashboard/components/DashboardCards/AuthorizedStudies/ListItem/index.tsx
src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx

[SJIP-567](https://d3b.atlassian.net/browse/SJIP-567)
You can see the video in the ticket (too big to upload it here).

fix(studies): SJIP-567 fix links to exploration

---

package-lock.json
src/graphql/biospecimens/models.ts
src/graphql/biospecimens/queries.ts
src/graphql/participants/models.ts
src/graphql/participants/queries.ts
src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
src/views/ParticipantEntity/utils/biospecimens.tsx

:bug: Rename volume_ul to volume

---

src/services/api/user/index.ts
src/views/Community/index.tsx

- closes [#SJIP-603](https://d3b.atlassian.net/browse/SJIP-603)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-603)
Fix issues when navigating on multiple page and then applying filters don't work.
@kstonge

fix: SJIP-603 filter now works with multiple page

---

src/locales/en.ts
src/store/savedSet/index.ts
src/views/Dashboard/components/DashboardCards/BiospecimenRequests/ListItem.tsx
src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
src/views/DataExploration/utils/constant.ts

- closes SJIP-617
https://d3b.atlassian.net/browse/SJIP-617

fix: SJIP-617 fix biospecimen set and biospecimen request set id field

---

src/components/Biospecimens/Request/NoSampleModal.tsx
src/components/Biospecimens/Request/RequestBiospecimenModal.tsx
src/components/Biospecimens/Request/RequestBiospecimenTable.tsx
src/components/Biospecimens/Request/requestBiospecimen.module.scss
src/locales/en.ts
src/style/themes/include/antd/alerts.less

[SJIP-577](https://d3b.atlassian.net/browse/SJIP-577)
- font weight on alert title
- modal width
- add available samples tooltip
- typo

fix(bioreq): SJIP-577 QA fixes

---

src/views/ProfileSettings/cards/Identification/index.tsx
src/views/ProfileSettings/index.tsx

[SJIP-622](https://d3b.atlassian.net/browse/SJIP-622)
We need to be able to save our profile without public email.
https://github.com/include-dcc/include-portal-ui/assets/133775440/ef65107c-5e8b-45b4-bf24-e755b7c26673
https://github.com/include-dcc/include-portal-ui/assets/133775440/543d5888-6273-4601-aebb-59385361476b

fix(profile): SJIP-622 save null email

---

src/components/Biospecimens/Request/RequestBiospecimenButton.tsx
src/components/Biospecimens/Request/RequestBiospecimenModal.tsx
src/locales/en.ts
src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx

[SJIP-633](https://d3b.atlassian.net/browse/SJIP-633)
Improve wording

fix(bioreq): SJIP-633 wording

---

src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx
src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx

[SJIP-582](https://d3b.atlassian.net/browse/SJIP-582)
Upload ids must be insensitive : 
- participants
- biospecimens
- files

fix(dataexplo): SJIP-582 upload ids case sensitive

---

src/locales/en.ts
src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx
src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx

[SJIP-635](https://d3b.atlassian.net/browse/SJIP-635)
Update tooltip to include Variants for filters and sets widget.

feat(dashboard): SJIP-635 update widget tooltip

---

package-lock.json
package.json
src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
src/views/DataExploration/components/UploadIds/utils.tsx

[SJIP-582](https://d3b.atlassian.net/browse/SJIP-582)
Back from QA, insensitive case was good but result is empty even if we had match.

fix(upload): SJIP-582 file upload ids

---

package-lock.json
package.json
src/auth/keycloak-api/keycloak.ts

SJIP-640 [Keycloak] Update Keycloak to latest version

feat: SJIP-640 upgrade keycloak dependancy

---

src/views/Studies/index.tsx

- complements #SJIP-594
Modify the data-row-key of the Studies table to have a data-row-key determined for Cypress tests.

feat: SJIP-594 Modify data-row-key Studies table

---

cypress/e2e/Consultation/PageParticipant.cy.ts
cypress/e2e/Consultation/PageVariant.cy.ts
cypress/e2e/Consultation/TableauBiospecimens.cy.ts
cypress/e2e/Consultation/TableauFiles.cy.ts
cypress/e2e/Consultation/TableauParticipants.cy.ts
cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Facettes/PageDataExploration.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- closes #[SJIP-679](https://d3b.atlassian.net/browse/SJIP-679)
Plusieurs modifications accumulées.

feat: SJIP-679 Add and adjust Cypress tests

---

src/views/Variants/components/PageContent/VariantsTable/index.tsx

[SJIP-662](https://d3b.atlassian.net/browse/SJIP-662)
- Use `internal_frequencies.total.pf` instead of `af`

feat(variants): SJIP-662 fix part frequency

---

src/views/Variants/components/PageContent/VariantsTable/index.tsx

[SJIP-662](https://d3b.atlassian.net/browse/SJIP-662)
- Remove dbsnp sort

fix(variants): SJIP-662 remove dbsnp sort

---

src/style/themes/include/antd/tables.less

[SJIP-693](https://d3b.atlassian.net/browse/SJIP-693)
- In fixed columns, line colors must be alternated. (sorted or not, selected or not)

fix(style): SJIP-693 fixed column color

---

src/graphql/biospecimens/queries.ts
src/graphql/files/queries.ts
src/graphql/participants/queries.ts
src/locales/en.ts
src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx
src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx

[SJIP-681](https://d3b.atlassian.net/browse/SJIP-681)
- Participant upload ids has no result => fix query
- Participant upload ids display study id instead of study code
- Same for file and biospecimen upload ids
Participant
Biospecimen
File

fix(upload): SJIP-681 use study code

---

src/locales/en.ts

- closes [#SJIP-652](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-652)
[[JIRA LINK]](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-652)

fix: SJIP-652 change no data available message to be consistent

---

src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx

- closes [#SJIP-581](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-581)
[[JIRA LINK]](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-581)

fix: SJIP-581 adjust capitalization on Data Access column and make it sortable

---

src/locales/en.ts
src/utils/translation.ts

[SJIP-601](https://d3b.atlassian.net/browse/SJIP-601)
- Facet and query pill must have the same name

fix(wording): SJIP-601 facet and pill name

---

src/views/DataExploration/index.tsx

- closes [#SJIP-677](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-677)
[[JIRA LINK]](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-677)

feat: SJIP-677 add parent sample type as a facet

---

package-lock.json
package.json

- closes [#SJIP-561)](https://d3b.atlassian.net/browse/SJIP-561)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-561)

fix: SJIP-561 fix the operator tooltip in QueryBuild

---

src/views/Studies/index.tsx

- closes [#SJIP-702](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-702)
add missing sorting on dbGaP column in studies after QA review
[[JIRA LINK]](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-702)

fix: SJIP-702 add missing sorting on dbGaP column in studies

---

package-lock.json
package.json
src/graphql/files/models.ts
src/graphql/files/queries.ts
src/graphql/participants/models.ts
src/graphql/utils/helpers.test.ts
src/graphql/utils/helpers.ts
src/helpers/helpers.test.ts
src/helpers/index.ts
src/services/api/cavatica/index.ts
src/store/fenceCavatica/thunks.test.ts
src/store/fenceCavatica/thunks.tsx
src/utils/helper.test.ts
src/utils/helper.ts

- closes [#SJIP-703](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-703)
[[JIRA LINK]](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-703)

feat: SJIP-703 extract metadata from data files and upload to cavatica

---

src/store/fenceCavatica/thunks.test.ts
src/store/fenceCavatica/thunks.tsx

- closes [#SJIP-703](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-703)
need to change name to prevent error

fix: SJIP-703 change metadata property name to fix bulk import

---

src/components/Biospecimens/DownloadDataButton/index.tsx
src/components/Biospecimens/Request/RequestBiospecimenButton.tsx
src/components/Cavatica/AnalyzeButton/index.tsx
src/components/reports/DownloadClinicalDataDropdown/index.tsx
src/components/uiKit/reports/DownloadFileManifestModal/index.tsx
src/locales/en.ts
src/views/DataExploration/components/SetsManagementDropdown/index.tsx

- closes [#SJIP-706](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-706)

feat: SJIP-706 add tooltip to disabled state buttons

---

package-lock.json
package.json

Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/395

chore(package): SJIP-715 update package json

---

src/store/user/thunk.test.ts
src/store/user/thunks.ts
src/store/user/thunksTestData.ts

- closes #[717](https://d3b.atlassian.net/browse/SJIP-717)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-717)
Fix le p'tit bouton
https://github.com/include-dcc/include-portal-ui/assets/65532894/8cb92f4a-586b-4104-8632-e1836bef7e66

fix(config): SJIP-717 fix config user update

---

src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx

- closes #[716](https://d3b.atlassian.net/browse/SJIP-716)
https://d3b.atlassian.net/browse/SJIP-716

fix(graph): SJIP-716 fix legend margin

---

src/App.tsx
src/services/api/study/index.ts
src/services/api/study/model.ts
src/store/index.tsx
src/store/study/index.ts
src/store/study/selector.ts
src/store/study/slice.ts
src/store/study/thunks.ts
src/store/study/type.ts
src/store/types.ts
src/utils/routes.ts
src/views/StudyEntity/index.tsx

Ajoute uniquement la route vers la nouvelle page study entity

feat(study): SJIP-709 add study page route

---

src/locales/en.ts
src/locales/fr.ts
src/views/Login/index.tsx

[SJIP-722](https://d3b.atlassian.net/browse/SJIP-722)
- add space before and after "new insights"

fix(landing): SJIP-722 fix typo

---

src/store/report/thunks.tsx

- closes [#SJIP-726](https://d3b.atlassian.net/jira/software/c/projects/SJIP/boards/93?selectedIssue=SJIP-726)

fix: SJIP-726 Adjust Track Report Download format in GA4

---

src/views/DataExploration/utils/helper.tsx
src/views/StudyEntity/index.tsx
src/views/StudyEntity/utils/dataAccess.tsx

[SJIP-710](https://d3b.atlassian.net/browse/SJIP-710)
1. La section devrait être présente dans le menu dynamique
2. Il manque les hyperliens sur les codes DUO
3. Ajouter un espace entre chaque contact

fix(study): SJIP-710 add DUO link

---

src/style/themes/include/colors.less

[SJIP-733](https://d3b.atlassian.net/browse/SJIP-733)
- Update lime colors

feat(colors): SJIP-733 update lime colors

---

package-lock.json
package.json
src/graphql/summary/queries.ts
src/locales/en.ts
src/views/StudyEntity/index.tsx

Goal: Add the Summary Statistics section to give a quick overview of the available data provided by a study. Note that we will not allow the Drag, resize, Addition or remove through chart selection tool in this page contrary to the summary view in the data exploration page.
https://www.notion.so/ferlab/Study-Entity-Page-ca49972b492e4389a9712f1927cc1a4d?pvs=4#df8983de174c43c79867425ea9a3a786
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-711)
https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/410
https://github.com/include-dcc/include-portal-ui/assets/65532894/2b0290e2-f6db-4a9d-9864-d0228d7e96f7

Feat/sjip 711/summary statistic

---

src/views/StudyEntity/utils/summary.tsx

- closes #[709](https://d3b.atlassian.net/browse/SJIP-709)
. Les hyperliens de Publication ne fonctionnent pas
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-709)

fix(study): SJIP-709 fix summary publication redirection

---

src/locales/en.ts
src/views/StudyEntity/SummaryHeader/index.module.scss
src/views/StudyEntity/SummaryHeader/index.tsx
src/views/StudyEntity/index.tsx

[SJIP-729](https://d3b.atlassian.net/browse/SJIP-729)
- Add summary header
-

feat(study): SJIP-729 add summary header

---

package-lock.json
package.json

- closes #[128](https://ferlab-crsj.atlassian.net/browse/FLUI-128)
Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/413

chore(package): FLUI-128 update package

---

src/graphql/studies/queries.ts
src/services/api/user/models.ts
src/views/Studies/components/PageContent/index.module.scss
src/views/Studies/components/PageContent/index.tsx
src/views/Studies/components/SideBarFacet/index.module.scss
src/views/Studies/components/SideBarFacet/index.tsx
src/views/Studies/components/StudySearch/index.tsx
src/views/Studies/index.module.scss
src/views/Studies/index.tsx
src/views/Studies/utils/constants.ts

- closes #[751](https://d3b.atlassian.net/browse/SJIP-751)
Add facets to studies page
https://www.notion.so/ferlab/Study-Page-V2-d1d5a7590ed04ae195bfbf73afa6c769

feat(studies): SJIP-571 add facets to studies page

---

src/locales/en.ts

[SJIP-757](https://d3b.atlassian.net/browse/SJIP-757)
- Add title Studies

feat(studies): SJIP-757 add title

---

src/components/uiKit/FilterList/CustomFilterContainer.tsx
src/components/uiKit/FilterList/index.tsx
src/views/Studies/components/SideBarFacet/index.tsx

[SJIP-755](https://d3b.atlassian.net/browse/SJIP-755)
- remove apply button of facets
https://github.com/include-dcc/include-portal-ui/assets/133775440/9076ae0c-2049-4d44-92d1-fd7ac9cbe045

feat(studies): SJIP-755 remove apply button facet

---

package-lock.json
package.json
src/locales/en.ts
src/utils/query.ts
src/utils/translation.ts
src/views/Community/index.tsx
src/views/Studies/components/PageContent/index.module.scss
src/views/Studies/components/PageContent/index.tsx
src/views/Studies/components/SideBarFacet/index.module.scss
src/views/Studies/index.tsx

[SJIP-756](https://d3b.atlassian.net/browse/SJIP-756)
- remove Query Builder
- add sesrch box
- fix result typo

feat(studies): SJIP-756 remove QB and add search box

---

src/views/Studies/components/PageContent/index.tsx

[SJIP-756](https://d3b.atlassian.net/browse/SJIP-756)
- search box case insensitive

fix(studies): SJIP-756 remove case sensitive

---

src/style/themes/include/antd-include-theme.less
src/style/themes/include/antd/buttons.less

- closes [#SJIP-763](https://d3b.atlassian.net/browse/SJIP-763)
Before:
After:

fix: SJIP-763 update link and button link styles to match ui kit

---

src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/views/Studies/index.tsx
src/views/StudyEntity/utils/dataAccess.tsx
src/views/StudyEntity/utils/datasets.tsx
src/views/StudyEntity/utils/summary.tsx

[SJIP-770](https://d3b.atlassian.net/browse/SJIP-770)
- Fix studies and study pages

fix(study): SJIP-770 fix after mock

---

src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/views/StudyEntity/index.module.scss
src/views/StudyEntity/utils/file.tsx
src/views/StudyEntity/utils/summary.tsx

[SJIP-770](https://d3b.atlassian.net/browse/SJIP-770)
- use domains and external ids in summary section
- use mock in file section

fix(study): SJIP-770 file section use mock

---

package-lock.json
package.json
src/views/StudyEntity/index.tsx

Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/421
Add to the excluded MONDO terms list: trisomy 21 MONDO:0700126 (added to notion list)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-773)

feat(statistic): SJIP-773 add excludeZeroValue to statistic graph

---

src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx

- closes #[749](https://d3b.atlassian.net/browse/SJIP-749)
Au Delete avec le X, ce n’est pas le bon graph qui est retiré de la vue.
[[JIRA LINK]
](https://d3b.atlassian.net/browse/SJIP-749)
https://github.com/include-dcc/include-portal-ui/assets/65532894/5dd65762-3da9-4adb-bb9f-cef6a4e5ae98

fix(summary): SJIP-749 fix sample_type id

---

src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx

fix(summary): SJIP-749 fix uuid

---

package-lock.json
package.json
src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/locales/en.ts
src/views/StudyEntity/index.tsx
src/views/StudyEntity/utils/summary.tsx

[SJIP-775](https://d3b.atlassian.net/browse/SJIP-775)
- Add harmonized tag in summary beside study name
- Add harmonized tag in dataset header

feat(study): SJIP-775 add harmonized tags

---

src/views/Studies/index.tsx

[SJIP-750](https://d3b.atlassian.net/browse/SJIP-750)
- Link studies to study
https://github.com/include-dcc/include-portal-ui/assets/133775440/546efc1d-fcb1-4cdc-b335-d7caa517ad57

feat(studies): SJIP-750 link studies to study

---

src/views/StudyEntity/index.module.scss
src/views/StudyEntity/utils/summary.tsx

[SJIP-766](https://d3b.atlassian.net/browse/SJIP-766)
- update icon color

fix(study): SJIP-766 info icon style

---

src/locales/en.ts

fix(study): SJIP-776 fix typo

---

src/locales/en.ts
src/views/Studies/index.tsx

[SJIP-787](https://d3b.atlassian.net/browse/SJIP-787)
- fix typo in harmonized tooltip
[SJIP-765](https://d3b.atlassian.net/browse/SJIP-765)
- fix domains display in studies column

fix(study): SJIP-787 SJIP-765 fixes

---

src/graphql/studies/queries.ts
src/views/Studies/index.tsx

[SJIP-789](https://d3b.atlassian.net/browse/SJIP-789)
- add files column
https://github.com/include-dcc/include-portal-ui/assets/133775440/2c7b8020-fe08-45b0-8c7a-4fc9291e0f30

feat(studies): SJIP-789 add files column

---

package-lock.json
package.json
src/locales/en.ts
src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx
src/views/Dashboard/components/DashboardCards/Cavatica/index.tsx

https://d3b.atlassian.net/browse/SJIP-783
See https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/427

fix(widget): SJIP-783 add disconnect to error message

---

src/views/Studies/index.tsx

[SJIP-765](https://d3b.atlassian.net/browse/SJIP-765)
- add ellipsis to description

fix(studies): SJIP-765 fix description display

---

package-lock.json
package.json

Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/428

feat(entity): SJIP-791 Fix phenotypes and mondo graph to display empty data

---

src/graphql/studies/models.ts
src/graphql/studies/queries.ts

fix(studies): SJIP-795 remove domain

---

package-lock.json
package.json
src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx

Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/429

fix(widget): SJIP-796 fix disconnect button

---

package-lock.json
package.json
src/views/StudyEntity/SummaryHeader/index.module.scss

[SJIP-797](https://d3b.atlassian.net/browse/SJIP-797)
- align statistic icon

fix(study): SJIP-797 statistic align

---

src/views/StudyEntity/utils/datasets.tsx

[SJIP-797](https://d3b.atlassian.net/browse/SJIP-797)
- remove empty dataset lines

fix(study): SJIP-797 remove empty dataset lines

---

package-lock.json
package.json
src/locales/en.ts
src/views/VariantEntity/index.module.scss
src/views/VariantEntity/utils/summary.tsx

[SJIP-809](https://d3b.atlassian.net/browse/SJIP-809)
- If no ensembl_transcript_id remove the link
- If symbol = NO_GENE remove link and display “No gene”
- If NO_GENE remove - for aa_change

feat(variant): SJIP-809 no gene display in banner

---

src/views/Studies/index.tsx

[SJIP-794](https://d3b.atlassian.net/browse/SJIP-794)
- add dash to empty cells

fix(studies): SJIP-794 add dash for empty cells

---

src/locales/en.ts

[SJIP-813](https://d3b.atlassian.net/browse/SJIP-813)
- add of before INCLUDE

fix(landing): SJIP-813 typo in variant tile

---

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx

[SJIP-790](https://d3b.atlassian.net/browse/SJIP-790)
- study code sort in each tab
- sample availability in biospecimen tab

fix(dataexplo): SJIP-790 sort

---

package-lock.json
package.json
src/store/passport/slice.ts

Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/434

feat(cavatica): SJIP-758 add loading state for copy cavatica files

---

src/views/VariantEntity/index.module.scss

- closes [#SJIP-816](https://d3b.atlassian.net/browse/SJIP-816)
https://github.com/include-dcc/include-portal-ui/assets/156684667/ff6d325f-1967-47cb-97a7-e77a57a8b21a

fix: SJIP-816 adjust hover on tables

---

package-lock.json
package.json

- closes [#SJIP-818](https://d3b.atlassian.net/browse/SJIP-818)

fix: SJIP-818 implement svg download for charts

---

src/views/Studies/components/PageContent/index.tsx

- closes [#SJIP-792](https://d3b.atlassian.net/browse/SJIP-792)

fix: SJIP-792 prevent infinite re-render when searching in studies

---

src/services/analytics.ts
src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/GraphContent/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/TreePanel/index.tsx

- closes #[826](https://d3b.atlassian.net/browse/SJIP-826)

feat(sunburst): SJIP-826 add sunburst analytics

---

package-lock.json
package.json
src/utils/translation.ts
src/views/StudyEntity/index.tsx

- closes [#SJIP-803](https://d3b.atlassian.net/browse/SJIP-803)

feat: SJIP-803 allow download of Entity Statistic charts

---

src/views/Login/TopBanner/MondoChart/index.tsx

- closes [#SJIP-768](https://d3b.atlassian.net/browse/SJIP-768)

fix: SJIP-768 add mondo name on bar hover

---

package-lock.json
package.json
src/views/StudyEntity/utils/file.tsx

- closes [#SJIP-800](https://d3b.atlassian.net/browse/SJIP-800)

fix: SJIP-800 format some numbers in Study Entity

---

src/locales/en.ts
src/services/api/arranger/models.ts
src/views/Login/StudiesSection/DemographicGraphsCard/index.module.scss
src/views/Login/StudiesSection/DemographicGraphsCard/index.tsx
src/views/Login/StudiesSection/Stats/index.module.scss
src/views/Login/StudiesSection/index.module.scss
src/views/Login/StudiesSection/index.tsx

[SJIP-811](https://d3b.atlassian.net/browse/SJIP-811)
- add Demographic charts to login page

feat(login): SJIP-811 add demographic charts

---

package-lock.json
package.json

- closes [#SJIP-803](https://d3b.atlassian.net/browse/SJIP-803)

fix: SJIP-803 fix the format of Entity Statistic charts download and previews

---

src/views/Login/StudiesSection/DemographicGraphsCard/index.tsx

[SJIP-811](https://d3b.atlassian.net/browse/SJIP-811)
- Update T21 tooltips

fix(login): SJIP-811 update T21 tooltip

---

src/locales/en.ts
src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx
src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx

[SJIP-824](https://d3b.atlassian.net/browse/SJIP-824)
- Fix typo

fix(dashboard): SJIP-824 failed to fetch error msg

---

package-lock.json
package.json

- closes [#SJIP-831](https://d3b.atlassian.net/browse/SJIP-831)

fix: SJIP-831 remove max rows on Resizable Grid Layout

---

src/locales/en.ts

[SJIP-819](https://d3b.atlassian.net/browse/SJIP-819)
- typo in save tooltip

fix(qb): SJIP-819 tooltip typo

---

src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx

- closes [#SJIP-833](https://d3b.atlassian.net/browse/SJIP-833)

fix: SJIP-833 make demographics chart draggable in summary

---

cypress/e2e/Consultation/Landing.cy.ts
cypress/e2e/Consultation/TableauBiospecimens.cy.ts
cypress/e2e/Consultation/TableauFiles.cy.ts
cypress/e2e/Consultation/TableauParticipants.cy.ts
cypress/e2e/Consultation/TableauVariants.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- closes #SJIP-842
[SJIP-842](https://d3b.atlassian.net/browse/SJIP-842)

feat: SJIP-842 Adjust Cypress tests

---

src/views/Studies/components/PageContent/index.tsx

- closes [#SJIP-801](https://d3b.atlassian.net/browse/SJIP-801)

feat: SJIP-801 add option to search within a string in studies

---

src/views/Studies/components/PageContent/index.tsx

- closes [#SJIP-801](https://d3b.atlassian.net/browse/SJIP-801)

fix: SJIP-801 refactor search in the middle

---

src/graphql/files/queries.ts
src/graphql/participants/models.ts
src/graphql/participants/queries.ts
src/locales/en.ts
src/locales/fr.ts
src/store/passport/metadata.ts
src/store/passport/thunks.test.ts
src/utils/translation.ts
src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
src/views/ParticipantEntity/utils/getDiagnosisColumns.tsx

- closes [#SJIP-848](https://d3b.atlassian.net/browse/SJIP-848)

fix: SJIP-848 use mondo_display_term instead of old id

---

src/store/passport/metadata.ts
src/store/passport/thunks.test.ts

- closes [#SJIP-850](https://d3b.atlassian.net/browse/SJIP-850)

fix: SJIP-850 remove some cavatica metadata

---

cypress/e2e/Consultation/PageParticipant.cy.ts
cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/Consultation/TableauParticipants.cy.ts
cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Facettes/PageDataExploration.cy.ts
cypress/e2e/Facettes/PageStudies.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/e2e/Recherche/PageStudies.cyTODO.ts
cypress/e2e/Requetes/ValidationParticipants.cy.ts
cypress/fixtures/ExportTableauStudies.json
cypress/support/commands.ts

- closes #SJIP-859
[SJIP-859](https://d3b.atlassian.net/browse/SJIP-859)

feat: SJIP-859 Adjust Cypress tests

---

cypress/e2e/SaveSetButton/PageDataExploration.cy.ts
cypress/e2e/SaveSetButton/PageVariants.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- closes #SJIP-864
[SJIP-864](https://d3b.atlassian.net/browse/SJIP-864)

feat: SJIP-864 Add SaveSetButton Cypress tests

---

package-lock.json
package.json
src/views/DataExploration/components/TreeFacet/TreeFacetModal.tsx
src/views/DataExploration/components/TreeFacet/index.tsx
src/views/DataExploration/index.tsx

see https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/468

fix(ontology): SJIP-822 fix issues

---

cypress/e2e/Consultation/PageParticipant.cy.ts
cypress/e2e/Consultation/PageProfileSettings.cy.ts
cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Requetes/ActionsSur0Requete.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts
cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts
cypress/e2e/Requetes/ValidationParticipants.cy.ts
cypress/e2e/SaveSetButton/PageDataExploration.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- closes #SJIP-888
- complements #SJIP-886
[SJIP-888](https://d3b.atlassian.net/browse/SJIP-888)
[SJIP-886](https://d3b.atlassian.net/browse/SJIP-886)

feat: SJIP-888 Add Profile settings Cypress tests and adjustments

---

src/middleware/AuthMiddleware.tsx

[SJIP-890](https://d3b.atlassian.net/browse/SJIP-890)
- don't display error message just login page and redirect after
see video in ticket because are too big

feat(share): SJIP-890 manage share link not login

---

package-lock.json
package.json

see https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/479

chore(package): FLUI-135 update ferlab-ui

---

src/views/StudyEntity/utils/summary.tsx

SJIP-847: Fix publications link :bug:

---

src/store/savedSet/thunks.ts

- closes #[879](https://d3b.atlassian.net/browse/SJIP-879)
si on édite le nom et qu’on copie/colle le lien, il semble que l’objet est dédoublé.
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-879)
https://github.com/include-dcc/include-portal-ui/assets/65532894/a6830f15-d3ed-4bb3-afdc-d6c1137b2590

fix(bioreq): SJIP-879 fix duplicates when sharing a biospecimen request

---

cypress/e2e/Filtres/PageDataExploration.cy.ts
cypress/e2e/Filtres/PageVariants.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Widgets/SavedFilters.cy.ts

- closes #SJIP-899
[SJIP-899](https://d3b.atlassian.net/browse/SJIP-899)

feat: SJIP-899 Add Saved Filters Widget Cypress tests

---

cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Widgets/SavedFilters.cy.ts
cypress/e2e/Widgets/SavedSets.cy.ts

- closes #SJIP-900
[SJIP-900](https://d3b.atlassian.net/browse/SJIP-900)

feat: SJIP-900 Add Saved Sets Widget Cypress tests

---

src/locales/en.ts
src/locales/fr.ts

- closes [#SJIP-884](https://d3b.atlassian.net/browse/SJIP-884)

fix: SJIP-884 change casing on profile settings title

---

cypress/e2e/Consultation/PageProfileSettings.cy.ts

- closes #SJIP-901
- relate to #SJIP-884
[SJIP-901](https://d3b.atlassian.net/browse/SJIP-901)
[SJIP-884](https://d3b.atlassian.net/browse/SJIP-884)

feat: SJIP-901 Adjust Cypress tests related to SJIP-884

---

package-lock.json
package.json

- closes #[902](https://d3b.atlassian.net/browse/SJIP-902)
voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/485

chore(package): SJIP-902 update ferlab-ui

---

cypress/e2e/Widgets/CavaticaProjects.cy.ts

- closes #SJIP-903
[SJIP-903](https://d3b.atlassian.net/browse/SJIP-903)

feat: SJIP-903 Add Cavatica Widget Cypress tests

---

cypress/e2e/Widgets/AuthorizedStudies.cy.ts

- closes #SJIP-904
[SJIP-904](https://d3b.atlassian.net/browse/SJIP-904)

feat: SJIP-904 Add Authorized Studies Widget Cypress tests

---

cypress/e2e/Consultation/PageFile.cy.ts
cypress/e2e/Consultation/PageParticipant.cy.ts
cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/Consultation/TableauParticipants.cy.ts
cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Recherche/PageStudies.cy.ts
cypress/e2e/Requetes/ActionsSur0Requete.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts
cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts
cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
cypress/e2e/Requetes/ValidationParticipants.cy.ts
cypress/e2e/Telechargement/TableauParticipants.cy.ts
cypress/e2e/Telechargement/TableauxPageParticipant.cy.ts

- closes #SJIP-917
- relate to #SJIP-916
[SJIP-917](https://d3b.atlassian.net/browse/SJIP-917)
[SJIP-916](https://d3b.atlassian.net/browse/SJIP-916)

feat: SJIP-917 Adjust Cypress tests related to last ETL run and SJIP-916

---

cypress/e2e/Widgets/BiospecimenRequests.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- closes #SJIP-918
[SJIP-918](https://d3b.atlassian.net/browse/SJIP-918)

feat: SJIP-918 Add Widget Biospecimen Requests Cypress tests

---

cypress/e2e/Consultation/PageFile.cy.ts
cypress/e2e/Consultation/PageParticipant.cy.ts
cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/Consultation/TableauParticipants.cy.ts
cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Recherche/PageStudies.cy.ts
cypress/e2e/Requetes/ActionsSur0Requete.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts
cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts
cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
cypress/e2e/Requetes/ValidationParticipants.cy.ts
cypress/e2e/Telechargement/TableauParticipants.cy.ts
cypress/e2e/Telechargement/TableauxPageParticipant.cy.ts
cypress/fixtures/ExportTableauFamilyPageParticipant.json
cypress/fixtures/ExportTableauParticipants.json

- closes #SJIP-921
- relate to #SJIP-916
[SJIP-921](https://d3b.atlassian.net/browse/SJIP-921)
[SJIP-916](https://d3b.atlassian.net/browse/SJIP-916)

feat: SJIP-921 Adjust Cypress tests related to SJIP-916

---

src/views/DataExploration/index.tsx

fix: SJIP-933 Change react key for mondo tree facet

---

src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx

- closes [#TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-943)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-943)

fix(exploration): SJIP-943 fix source conditions text

---

cypress/e2e/CavaticaButton/PageDataExploration.cy.ts
cypress/e2e/CavaticaButton/PageFile.cy.ts

- closes #SJIP-951
[SJIP-951](https://d3b.atlassian.net/browse/SJIP-951)

feat: SJIP-951 Add Analyze in Cavatica button Cypress tests

---

package-lock.json
package.json
src/graphql/quickFilter/queries.ts
src/style/themes/include/main.css
src/utils/translation.ts
src/views/DataExploration/index.tsx
src/views/DataExploration/utils/quickFilter.ts

- @see https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/514
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-952)
Add quickfilter to includes
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-952)

feat(quickfilter): SJIP-952 add quickfilter

---

package-lock.json
package.json
src/locales/en.ts
src/style/themes/include/main.css
src/utils/translation.ts

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-952)
1. Le placeholder devrait être « Search… »
2. Le message devrait être « Min. 3 characters » 
3. Les couleurs ne semblent pas les bonnes

fix(quickfilter): SJIP-952 fix colors and texts

---

cypress/e2e/Consultation/TableauStudies.cy.ts

- closes #SJIP-966
[SJIP-966](https://d3b.atlassian.net/browse/SJIP-966)

feat: SJIP-966 Adjust Cypress tests related to new study

---

package-lock.json
package.json
src/locales/en.ts
src/services/api/transcriptomics/index.ts
src/services/api/transcriptomics/models.ts
src/store/analytics/index.ts
src/store/analytics/thunks.ts
src/store/analytics/types.ts
src/views/Analytics/Transcriptomic/ScatterPlotCanvas/index.tsx
src/views/Analytics/Transcriptomic/SwarmPlot/Layers/SelectBoxSvgLayer.tsx
src/views/Analytics/Transcriptomic/SwarmPlot/index.module.css
src/views/Analytics/Transcriptomic/SwarmPlot/index.tsx
src/views/Analytics/Transcriptomic/index.module.css
src/views/Analytics/Transcriptomic/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-955)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-955)

feat(transcriptomic): SJIP-955 add swarm plot chart

---

package-lock.json
package.json
src/App.tsx
src/locales/en.ts
src/views/Analytics/Transcriptomic/ScatterPlotCanvas/index.module.css
src/views/Analytics/Transcriptomic/ScatterPlotCanvas/index.tsx
src/views/Analytics/Transcriptomic/SearchByGene/index.tsx
src/views/Analytics/Transcriptomic/SearchBySample/index.tsx
src/views/Analytics/Transcriptomic/SwarmPlot/Layers/SelectBoxSvgLayer.tsx
src/views/Analytics/Transcriptomic/SwarmPlot/index.module.css
src/views/Analytics/Transcriptomic/SwarmPlot/index.tsx
src/views/Analytics/Transcriptomic/TranscriptomicSearch/index.tsx
src/views/Analytics/Transcriptomic/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-955)
[JIRA LINK]
https://github.com/user-attachments/assets/34633536-05d8-46b1-bc70-718f050ebc76

feat(transcriptomic): SJIP-955 sync search and graph

---

package-lock.json
package.json
src/locales/en.ts
src/services/api/transcriptomics/models.ts
src/views/Analytics/Transcriptomic/ScatterPlotCanvas/index.tsx
src/views/Analytics/Transcriptomic/SwarmPlot/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-955)
https://github.com/user-attachments/assets/df083a2e-4873-4e2a-9732-7945a35419ef

fix(plot): SJIP-955 fix zoom scaling behavior

---

src/locales/en.ts
src/views/Analytics/Transcriptomic/Dataset/index.module.css
src/views/Analytics/Transcriptomic/Dataset/index.tsx
src/views/Analytics/Transcriptomic/ScatterPlotCanvas/index.module.css
src/views/Analytics/Transcriptomic/ScatterPlotCanvas/index.tsx
src/views/Analytics/Transcriptomic/SwarmPlot/index.module.css
src/views/Analytics/Transcriptomic/SwarmPlot/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-954)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-954)

fix(scatter): SJIP-954 fix design and legend

---

package-lock.json
package.json
src/locales/en.ts
src/views/Analytics/Transcriptomic/Dataset/AboutModal/index.module.css
src/views/Analytics/Transcriptomic/Dataset/AboutModal/index.tsx
src/views/Analytics/Transcriptomic/Dataset/index.module.css
src/views/Analytics/Transcriptomic/Dataset/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-958)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-958)

feat(dataset): SJIP-958 add dataset modal

---

package-lock.json
package.json
src/views/Analytics/Transcriptomic/SwarmPlot/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-991)
Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/532
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-991)

fix(swarm): SJIP-991 update swarm layers

---

src/locales/en.ts
src/views/Analytics/Transcriptomic/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-993)
Update empty state
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-993)

feat(transcriptomic): SJIP-993 update empty state

---

cypress/e2e/CavaticaButton/PageDataExploration.cy.ts
cypress/e2e/Consultation/Landing.cy.ts
cypress/e2e/Consultation/PageFile.cy.ts
cypress/e2e/Consultation/PageParticipant.cy.ts
cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/Consultation/PageVariant.cy.ts
cypress/e2e/Consultation/TableauBiospecimens.cy.ts
cypress/e2e/Consultation/TableauFiles.cy.ts
cypress/e2e/Consultation/TableauParticipants.cy.ts
cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Consultation/TableauVariants.cy.ts
cypress/e2e/Facettes/PageDataExploration.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts
cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts
cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
cypress/e2e/Widgets/BiospecimenRequests.cy.ts
cypress/e2e/Widgets/SavedFilters.cy.ts
cypress/e2e/Widgets/SavedSets.cy.ts
cypress/support/commands.ts

feat: SJIP-994 Improved locators in Cypress tests

---

src/views/Studies/components/PageContent/index.module.css
src/views/Studies/components/PageContent/index.tsx

fix(studies): SJIP-1013 style

---

src/locales/en.ts

[SJIP-1027](https://d3b.atlassian.net/browse/SJIP-1027)
- remove space
- remove uppercase

fix(studies): SJIP-1027 typos

---

src/views/StudyEntity/index.tsx

- closes [#SJIP-989](https://d3b.atlassian.net/browse/SJIP-989)

feat: SJIP-989 display study statistics only if there is data

---

src/views/Studies/components/PageContent/Guid/utils.ts

[SJIP-1014](https://d3b.atlassian.net/browse/SJIP-1014)

fix(studies): SJIP-1014 update drs guid name

---

src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/locales/en.ts
src/store/passport/thunks.test.ts
src/utils/translation.ts
src/views/Studies/index.tsx

[SJIP-1023](https://d3b.atlassian.net/browse/SJIP-1023)
- Add GUID Type facet
- Add GUID tag and update tooltipof harmonized data column

feat(studies): SJIP-1023 add GUID Type facet and tag

---

src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/locales/en.ts
src/views/StudyEntity/utils/summary.tsx

[SJIP-1023](https://d3b.atlassian.net/browse/SJIP-1023)
- Add fields guid type, data categories, acknowledgement and citation statement

feat(study): SJIP-1023 add summary fields

---

src/locales/en.ts

[SJIP-1033](https://d3b.atlassian.net/browse/SJIP-1033)
- update tooltip on harmonized column
- remove uppercase on mapping file in guids modal

feat(studies): SJIP-1033 fix typo

---

src/locales/en.ts
src/views/Analytics/Transcriptomic/index.tsx

- closes [#SJIP-1030](https://d3b.atlassian.net/browse/SJIP-1030)
- closes [#SJIP-1031](https://d3b.atlassian.net/browse/SJIP-1031)

fix: SJIP-956 adjustments to transcriptomic facets

---

src/locales/en.ts

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-947)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-947)

fix(variant): SJIP-947 fix typo

---

src/locales/en.ts
src/views/Analytics/index.module.css
src/views/Analytics/index.tsx

[SJIP-990](https://d3b.atlassian.net/browse/SJIP-990)
- add space right and left on layout
- tag typo Gene

fix(analytics): SJIP-990 typo and layout

---

src/views/Analytics/NewsletterWidget/index.tsx

[SJIP-990](https://d3b.atlassian.net/browse/SJIP-990)
- harmoniser les messages d'erreur (defect 1041)

fix(analytics): SJIP-990 add specific error messages

---

src/locales/en.ts
src/views/DataExploration/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1043)
Participant
- Condition (Source Text)
- Vital Status
- Age at Diagnosis (days)
- Age at Vital Status (days)
- verify if we have data in the backend, normally we should
- Age at Observed Phenotype (days)
File
- ACL
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1043)

feat(facets): SJIP-1043 add facets

---

src/locales/en.ts

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1044)
Le label de la pilule devrait être le même que le titre de la facette
Ouvrir image-20241018-153639.png
image-20241018-153639.png
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1044)

fix(exploration): SJIP-1044 fix typo

---

src/locales/en.ts
src/views/Analytics/Transcriptomic/Footer/index.tsx
src/views/Analytics/Transcriptomic/Heatmaps/index.module.css
src/views/Analytics/Transcriptomic/Heatmaps/index.tsx
src/views/Analytics/Transcriptomic/ScatterPlot/index.tsx
src/views/Analytics/Transcriptomic/SearchByGene/index.tsx
src/views/Analytics/Transcriptomic/SearchBySample/index.tsx
src/views/Analytics/Transcriptomic/SwarmPlot/index.tsx
src/views/Analytics/Transcriptomic/TranscriptomicSearch/index.tsx
src/views/Analytics/Transcriptomic/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1035)
- Add multiselect for search by gene
- Add select box for graph
- Sync both fields
- Add heatmap
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1035)

feat(transcriptomic): SJIP-1035 add multi-select

---

src/locales/en.ts

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1049)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1049)

fix(transcriptomic): SJIP-1049 fix typo

---

cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Facettes/PageDataExploration.cy.ts
cypress/e2e/Facettes/PageStudies.cy.ts
cypress/e2e/ManifestButton/PageStudy.cy.ts
cypress/e2e/Telechargement/ClinicalDataPageParticipant.cy.ts
cypress/e2e/Telechargement/ClinicalDataPageStudy.cy.ts
cypress/e2e/Telechargement/ClinicalDataTableauParticipants.cy.ts
cypress/e2e/Telechargement/SampleDataPageParticipant.cy.ts
cypress/fixtures/DownloadClinicalData.json
cypress/fixtures/DownloadClinicalDataFamily.json
cypress/fixtures/DownloadClinicalDataStudy.json
cypress/fixtures/DownloadClinicalDataStudyFamily.json
cypress/fixtures/DownloadSampleDataParticipant.json

feat: SJIP-1062 Adjust Cypress tests related to recent changes

---

src/components/uiKit/Uploads/GeneUploadIds/index.tsx
src/components/uiKit/Uploads/SampleUploadIds/index.tsx
src/locales/en.ts
src/services/api/transcriptomics/index.ts
src/views/Analytics/Transcriptomic/SearchByGene/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1049)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1049)

fix(transcriptomic): SJIP-1049 impove uploads gene ids

---

src/locales/en.ts

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-992)
Le titre devrait être « Search by sample »
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-992)

fix(transcriptomic): SJIP-992 fix typo

---

src/views/Studies/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1065)
Afficher « See more » si plus d’un dbGaP.
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1065)

fix(study): SJIP-1065 add expand cell

---

src/views/Analytics/Transcriptomic/SearchByGene/index.tsx
src/views/Analytics/Transcriptomic/SearchBySample/index.tsx

feat(transcriptomic): SJIP-000 temp fix to hide filter button

---

src/components/uiKit/Uploads/GeneUploadIds/index.tsx
src/components/uiKit/Uploads/SampleUploadIds/index.tsx
src/views/Analytics/Transcriptomic/SearchByGene/index.tsx
src/views/Analytics/Transcriptomic/SearchBySample/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1060)
Le place holder dans la modal d’upload a gene list devrait être « e.g. BRAF, ENSG00000157764 » selon [l’analyse](https://www.notion.so/ferlab/Study-Specific-Transcriptomic-Analysis-77ae9bafe58d43278f486bf15b6139e0?pvs=4#7ae9c889b74345079b95a2d18793afb8).
Le place holder de la modal d’upload a sample list devrait être « e.g. bs-z8p7wjm7 » selon [l’analyse](https://www.notion.so/ferlab/Study-Specific-Transcriptomic-Analysis-77ae9bafe58d43278f486bf15b6139e0?pvs=4#cc554d57282b45518ab69ef2b8b4bc47).
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1060)

fix(transcriptomic): SJIP-1049 fix placeholder

---

src/components/uiKit/Uploads/SampleUploadIds/index.tsx

- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SJIP-1061)
La recherche du sample upload list devrait être case insensitive
[[JIRA LINK]](https://d3b.atlassian.net/browse/SJIP-1061)

fix(upload): SJIP-1061 sample ids should not be case sensitive

---

src/views/Variants/components/VariantGeneSearch/index.tsx

[SJIP-1069](https://d3b.atlassian.net/browse/SJIP-1069)
- When I lost focus on auto complete we want to empty suggestion list
https://github.com/user-attachments/assets/7cc1fe64-0c41-4f38-9204-842d7725eb8e
https://github.com/user-attachments/assets/864696ea-a735-4906-aae7-23fbe199b4c6

fix(variant): SJIP-1069 empty suggestion on close

---

src/locales/en.ts
src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx
src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx

[SJIP-935](https://d3b.atlassian.net/browse/SJIP-935)
- On top of the alphanumeric characters, only the following characters are allowed: ( ) [ ] - _ : | . , '

feat(sets): SJIP-935 validate permitted characters

---

package-lock.json
package.json
src/components/uiKit/FilterList/CustomFilterContainer.tsx
src/components/uiKit/FilterList/index.tsx
src/components/uiKit/FilterList/types.ts
src/views/DataExploration/index.module.css
src/views/DataExploration/index.tsx

- Closes SJIP-281
- [JIRA](https://d3b.atlassian.net/browse/SJIP-281)
1. 
2.

feat(facet qf): SJIP-281 add category icon

---

.github/workflows/create_pr_template.yml

- Closes SJIP-1079
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1079)
1. 
2.

feat: SJIP-1079 dynamic pr template

---

package-lock.json
package.json
src/components/uiKit/Uploads/GeneUploadIds/index.tsx
src/components/uiKit/Uploads/SampleUploadIds/index.tsx

- Closes SJIP-1090
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1090)

fix(upload): SJIP-1090 SJIP-1091 add text transform mode

---

package-lock.json
package.json
src/index.js

- Closes SJIP-1096
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1096)
1. 
2.

feat: SJIP-1096 add sentry mirror kf

---

cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Requetes/ActionsSur0Requete.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts
cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts
cypress/e2e/Requetes/ValidationParticipants.cy.ts
cypress/e2e/UploadList/PageVariants.cy.ts

- Closes SJIP-1101
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1101)
1. 
2.

feat: SJIP-1101 Adjust Cypress tests related to last ETL run

---

src/views/DataExploration/utils/quickFilter.ts

[SJIP-1102](https://d3b.atlassian.net/browse/SJIP-1102)
Sentry errors links : 
[https://ferlab.sentry.io/issues/6078268985/?project=4506264491786240&query=is%3Aunresolved issue.priority%3A[high%2C medium]&referrer=issue-stream&statsPeriod=14d&stream_index=1](https://ferlab.sentry.io/issues/6078268985/?project=4506264491786240&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1)
[https://ferlab.sentry.io/issues/6079925400/?project=4506264491786240&query=is%3Aunresolved issue.priority%3A[high%2C medium]&referrer=issue-stream&statsPeriod=14d&stream_index=2](https://ferlab.sentry.io/issues/6079925400/?project=4506264491786240&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&str …

fix(sentry): SJIP-1102 undefined object

---

package-lock.json
package.json

- Closes SJIP-1091
With textTransform props, the transformed text was displayed instead of the raw input
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1091)
-  https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/554

fix(uploads): SJIP-1091 display raw input for unmatch list

---

src/locales/en.ts
src/store/global/slice.ts
src/store/report/thunks.tsx
src/views/Variants/components/PageContent/VariantsTable/index.module.css
src/views/Variants/components/PageContent/VariantsTable/index.tsx
src/views/Variants/components/PageContent/VariantsTable/utils.tsx

[SJIP-666](https://d3b.atlassian.net/browse/SJIP-666)
Add tsv export
- tsv export
- limit modal
NA

feat(variants): SJIP-666 add TSV export

---

cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/UploadList/PageVariants.cy.ts

- Closes SJIP-1112
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1112)
1. 
2.

feat: SJIP-1112 Adjust Cypress tests related to recent changes

---

src/App.tsx
src/components/Layout/Footer/index.tsx
src/components/PublicLayout/Header/HeaderButton/index.module.css
src/components/PublicLayout/Header/HeaderButton/index.tsx
src/components/PublicLayout/Header/index.module.css
src/components/PublicLayout/Header/index.tsx
src/components/PublicLayout/index.module.css
src/components/PublicLayout/index.tsx
src/utils/routes.ts
src/views/PublicStudies/index.tsx

[SJIP-1105](https://d3b.atlassian.net/browse/SJIP-1105)
Implement public studies page.
- Create route / page
- Add header
NA

feat(public studies): SJIP-1105 Add header

---

src/locales/en.ts
src/services/api/arranger/models.ts
src/store/global/thunks.ts
src/views/Login/StudiesSection/index.tsx
src/views/PublicStudies/components/PageContent/index.module.css
src/views/PublicStudies/components/PageContent/index.tsx
src/views/PublicStudies/index.module.css
src/views/PublicStudies/index.tsx
src/views/PublicStudies/utils.tsx
src/views/Studies/index.tsx

- Closes SJIP-1104
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1104)
1. 
2.

feat(public): SJIP-1104 Add page content

---

src/views/PublicStudies/utils.tsx

[SJIP-1104](https://d3b.atlassian.net/browse/SJIP-1104)
- Add link on Participant and File columns

fix(studies): SJIP-1104 add empty links on part and file

---

commitlint.config.js

- Closes SJIP-1123
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1123)
1. 
2.

fix: SJIP-1123 commit number to commitlint

---

src/components/Icons/IncludeIcon.tsx
src/components/PublicLayout/Header/index.tsx
src/components/PublicLayout/LoginModal/index.module.css
src/components/PublicLayout/LoginModal/index.tsx
src/locales/en.ts
src/views/PublicStudies/components/PageContent/index.tsx
src/views/PublicStudies/utils.tsx

[SJIP-1106](https://d3b.atlassian.net/browse/SJIP-1106)
Add login modal for public pages
- Implement modal
- Open modal in header and on table link
NA

feat(studies): SJIP-1106 add login modal

---

src/locales/en.json
src/locales/en.ts
src/locales/fr.ts
src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx
src/views/DataExploration/components/UploadIds/EntityUploadIds/index.tsx
src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx

- Closes SJIP-860
Fix typo
- [JIRA](https://d3b.atlassian.net/browse/SJIP-860)

fix(upload): SJIP-860 fix typo

---

cypress/e2e/UploadList/PageDataExploration.cy.ts
cypress/e2e/UploadList/PageVariants.cy.ts

- Closes SJIP-1129
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1129)
1. 
2.

feat: SJIP-1129 Adjust Cypress tests related to SJIP-860

---

src/components/PublicLayout/LoginModal/index.module.css
src/components/PublicLayout/LoginModal/index.tsx
src/locales/en.ts

[SJIP-1106](https://d3b.atlassian.net/browse/SJIP-1106)
[SJIP-1128](https://d3b.atlassian.net/browse/SJIP-1128)
- Login modal typo
- Login modal close btn style
- typo
- style

fix(studies): SJIP-1106 close btn and style

---

src/components/PublicLayout/Header/index.tsx
src/components/PublicLayout/LoginModal/index.tsx
src/services/analytics.ts
src/views/Login/StudiesSection/index.tsx

[SJIP-1108](https://d3b.atlassian.net/browse/SJIP-1108)
Add Analytics
- in Landing page on view all studies button
- in Public studies page on all header buttons and on login modal buttons

feat(analytics): SJIP-1108 add GA on public studies page

---

src/views/Variants/components/PageContent/VariantsTable/index.tsx

[SJIP-1132](https://d3b.atlassian.net/browse/SJIP-1132)
- Display limit modal on select all
Before no modal.

fix(variants): SJIP-1132 add condition on TSV export

---

src/components/PublicLayout/Header/index.tsx

[SJIP-1130](https://d3b.atlassian.net/browse/SJIP-1130)
Add redirect to login.
Add link on header logo to login page
NA
https://github.com/user-attachments/assets/a7fb30cc-4096-4ce8-9eae-5bacb6a28c9c

feat(studies): SJIP-1130 add link to login in public layout header

---

cypress/e2e/Consultation/Landing.cy.ts
cypress/e2e/Navigation/Pages.cy.ts

- Closes SJIP-1133
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1133)
1. 
2.

feat: SJIP-1133 Adjust Cypress tests related to recent changes

---

src/locales/en.ts

- Closes SJIP-1125
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1125)

fix(landing): SJIP-1125 update text

---

cypress/e2e/UploadList/PageVariants.cy.ts

- Closes SJIP-1139
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1139)
1. 
2.

feat: SJIP-1139 Adjust Cypress tests related to SJIP-1127

---

cypress/e2e/Consultation/Landing.cy.ts

- Closes SJIP-1141
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1141)
1. 
2.

feat: SJIP-1141 Adjust Cypress tests related to SJIP-1125

---

src/views/VariantEntity/index.tsx
src/views/VariantEntity/utils/summary.tsx

- Closes SJIP-852
Add a new border property to the Descriptions Basic component (see [this FerLab ticket](https://ferlab-crsj.atlassian.net/browse/FLUI-131))
- [JIRA](https://d3b.atlassian.net/browse/SJIP-852)

feat(variant): SJIP-852 add bordered theme

---

src/views/PublicStudies/utils.tsx

[SJIP-1134](https://d3b.atlassian.net/browse/SJIP-1134)
Redirect to study entity on study code link
https://github.com/user-attachments/assets/f7953dca-ea26-4c1e-beca-a8e23f6d66bd

fix(studies): SJIP-1134 redirect to study entity in public studies page

---

cypress/e2e/Consultation/PageVariant.cy.ts

- Closes SJIP-1145
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1145)
1. 
2.

feat: SJIP-1145 Adjust Cypress tests related to SJIP-852

---

cypress/fixtures/ExportTableauFamilyPageParticipant.json

- Closes SJIP-1152
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1152)
1. 
2.

feat: SJIP-1152 Adjust Cypress tests related to recent changes

---

package-lock.json
package.json
src/components/uiKit/FilterList/CustomFilterContainer.tsx
src/components/uiKit/FilterList/index.tsx
src/components/uiKit/FilterList/types.ts
src/views/Variants/index.tsx

[SJIP-1154](https://d3b.atlassian.net/browse/SJIP-1154)
Define default range operators.
- Add default range operator for facet in variants page
Less than default value for all range facet.

feat(facet): SJIP-1154 default range operator

---

src/locales/en.ts
src/views/Variants/components/PageContent/VariantsTable/index.module.css
src/views/Variants/components/PageContent/VariantsTable/index.tsx
src/views/Variants/components/PageContent/VariantsTable/utils.tsx

[SJIP-1153](https://d3b.atlassian.net/browse/SJIP-1153)
Remove export tsv in variants page.
Remove export tsv in variants page.

feat(variants): SJIP-1153 remove export TSV

---

src/views/StudyEntity/utils/dataAccess.tsx
src/views/StudyEntity/utils/summary.tsx

- Closes SJIP-898
- [JIRA](https://d3b.atlassian.net/browse/SJIP-898)

feat(study): SJIP-898 move study contact to summary

---

src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/locales/en.ts
src/views/StudyEntity/index.tsx
src/views/StudyEntity/utils/dataAccess.tsx
src/views/StudyEntity/utils/datasets.tsx

[SJIP-1000](https://d3b.atlassian.net/browse/SJIP-1000)
Add fields
- Add new fields in dataset section
- Update with new ES fields

feat(study): SJIP-1000 add or update fields to dataset section

---

package-lock.json
package.json
src/components/uiKit/reports/DownloadClinicalDataDropdown.tsx
src/components/uiKit/reports/DownloadRequestAccessModal/index.tsx
src/services/api/transcriptomics/models.ts
src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx
src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx
src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
src/views/DataExploration/components/PageContent/index.tsx

[SJIP-1166](https://d3b.atlassian.net/browse/SJIP-1166)
Fix multiple error JS
- Nivo : Pie chart error on missing props
- Antd : Tab props implementation change
- Antd : deprecated props on modal and dropdown

fix(sentry): SJIP-1166 fix error JS

---

src/graphql/files/queries.ts
src/graphql/quickFilter/queries.ts
src/locales/en.ts
src/utils/translation.ts
src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
src/views/DataExploration/index.tsx

[SJIP-1001](https://d3b.atlassian.net/browse/SJIP-1001)
Add dataset in Data exploration page.
- Add facet in files section
- Add column in files tab
NA

feat(files): SJIP-1001 add dataset column and facet

---

src/components/Publication/index.tsx

[SJIP-1081](https://d3b.atlassian.net/browse/SJIP-1081)
Fix order
order publication most recent first
not ordered

fix(study): SJIP-1081 order publications

---

src/components/uiKit/reports/DownloadFileManifestModal/index.tsx
src/graphql/files/useFileResolvedSqon.tsx
src/locales/en.ts
src/utils/fieldMapper.ts
src/views/StudyEntity/index.module.css
src/views/StudyEntity/index.tsx

[SJIP-1004](https://d3b.atlassian.net/browse/SJIP-1004)
Add download manifest button
- Add button
- Remove checkbox in modal
- file name specific
NA

feat(study): SJIP-1004 add manifest btn in dataset section

---

src/components/uiKit/reports/DownloadFileManifestModal/index.tsx
src/views/StudyEntity/index.tsx

[SJIP-1003](https://d3b.atlassian.net/browse/SJIP-1003)
Add view in exploration in dataset section
- Add view in explo btn
NA
https://github.com/user-attachments/assets/ddd8a1f9-ebad-4197-9d9f-2ac6f39f1e02

feat(study): SJIP-1003 add dataset view in exploration btn

---

src/views/StudyEntity/index.tsx

- Closes SJIP-1003
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1003)
1. 
2.

fix(study): SJIP-1003 view in explo only if harmonized

---

cypress.config.ts

- Closes SJIP-1181
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1181)
1. 
2.

feat: SJIP-1181 Setup Ferlease Cypress execution

---

cypress/e2e/Widgets/AuthorizedStudies.cy.ts
src/locales/en.ts
src/locales/fr.ts

[SJIP-906](https://d3b.atlassian.net/browse/SJIP-906)
Fix typo

fix(auth studies): SJIP-906 typo

---

cypress/e2e/Widgets/AuthorizedStudies.cy.ts
src/locales/en.ts
src/locales/fr.ts

[SJIP-906](https://d3b.atlassian.net/browse/SJIP-906)
Soucis de linter, PR juste pour changer le commit message.

fix(authstudies): SJIP-906 typo

---

cypress/e2e/Consultation/PageStudy.cy.ts
src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/locales/en.ts
src/views/StudyEntity/utils/summary.tsx

[SJIP-1170](https://d3b.atlassian.net/browse/SJIP-1170)
Update GUID display with the new ES field.
- Update label GUID Available
- Use the new ES field is_guid_mapped and display tag true false

feat(study): SJIP-1170 update guid in summary

---

cypress/e2e/Consultation/PageStudy.cy.ts
src/components/Publication/PubModal/index.tsx
src/components/Publication/index.tsx
src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/views/StudyEntity/utils/datasets.tsx
src/views/StudyEntity/utils/summary.tsx

[SJIP-1185](https://d3b.atlassian.net/browse/SJIP-1185)
Update publication display for dataset in study entity
- Display citation
- Add modal if more than 1 publication
- Sort publication by date

feat(study): SJIP-1185 update publication in dataset

---

cypress/e2e/Facettes/PageStudies.cy.ts
src/graphql/studies/models.ts
src/graphql/studies/queries.ts
src/hooks/graphql/useGetExtendedMappings.ts
src/utils/translation.ts
src/views/Studies/index.tsx

[SJIP-1169](https://d3b.atlassian.net/browse/SJIP-1169)
Use new ES field for guid
- Update facet with is_guid_mapped
- Update column with is_guid_mapped

feat(studies): SJIP-1169 facet and column update for guid

---

src/services/api/arranger/models.ts
src/store/global/thunks.ts
src/views/PublicStudies/utils.tsx

[SJIP-1197](https://d3b.atlassian.net/browse/SJIP-1197)
Update ES field used to render GUID tag
- use new field is_guid_mapped

feat(studies): SJIP-1197 update guid tag with new ES field

---

cypress/e2e/Facettes/PageStudies.cy.ts

- Closes SJIP-1202
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1202)
1. 
2.

feat: SJIP-1202 Adjust Cypress tests related to last ETL run

---

package-lock.json
package.json
src/locales/en.ts
src/services/api/arranger/index.ts
src/store/index.tsx
src/store/savedSet/thunks.ts
src/store/types.ts
src/store/venn/index.ts
src/store/venn/selector.ts
src/store/venn/slice.ts
src/store/venn/thunks.ts
src/store/venn/types.ts
src/utils/translation.ts
src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx
src/views/DataExploration/components/PageContent/index.tsx

- Closes SJIP-1116
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1116)
- [Design](https://www.figma.com/design/TcTluY6XhFrv3WLtDSB6jY/Venn-Cohort-Compare?node-id=2187-33431&m=dev)

feat(query): SJIP-1116 add venn chart

---

cypress/e2e/Consultation/PageStudy.cy.ts
cypress/e2e/Consultation/TableauStudies.cy.ts
cypress/e2e/Facettes/PageStudies.cy.ts
cypress/e2e/Telechargement/TableauStudies.cy.ts
cypress/fixtures/DownloadClinicalDataStudy.json
cypress/fixtures/DownloadClinicalDataStudyFamily.json
cypress/fixtures/ExportTableauStudies.json

- Closes SJIP-1208
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1208)
1. 
2.

feat: SJIP-1208 Adjust Cypress tests related to recent changes

---

package-lock.json
package.json
src/locales/en.ts
src/services/analytics.ts
src/services/api/savedSet/models.ts
src/store/savedSet/thunks.ts
src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx
src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
src/views/DataExploration/components/PageContent/index.tsx
src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx

- Closes SJIP-1116
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1116)

feat(venn): SJIP-1116 add temporary set

---

cypress/support/commands.ts

- Closes SJIP-1247
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1247)
1. 
2.

feat: SJIP-1247 Adjust Cypress tests to fix some timing issues

---

src/views/StudyEntity/utils/summary.tsx

- Closes SJIP-1267
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1267)

fix(study): SJIP-1267 hide empty row

---

package-lock.json
package.json
src/locales/en.ts
src/style/themes/include/main.css
src/utils/translation.ts
src/views/DataExploration/index.tsx

[SKFP-1485](https://d3b.atlassian.net/browse/SJIP-1274)
Sentry error
Add validation on input search
--error--

fix(quickfilter): SJIP-1274 add validation on input search

---

commitlint.config.js

- Closes SJIP-00
- [JIRA](https://d3b.atlassian.net/browse/SJIP-00)
1. 
2.

fix: update commitlint config

---

src/index.js

[SJIP-1277](https://d3b.atlassian.net/browse/SJIP-1277)
Configure error send to sentry
Ignore some errors.

fix(sentry): SJIP-1277 add before send to catch non error

---

package-lock.json
package.json
src/locales/en.ts
src/views/Studies/components/PageContent/index.module.css
src/views/Studies/components/PageContent/index.tsx
src/views/Studies/index.tsx

- Closes SJIP-1190
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1190)

feat(studies): SJIP-1190 add summary

---

cypress/e2e/Consultation/TableauStudies_1.cy.ts

- Closes SJIP-1286
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1286)
1. 
2.

feat: SJIP-1286 Add Cypress tests related to SJIP-1190

---

cypress/e2e/Colonnes/TableauStudies.cy.ts
cypress/e2e/Consultation/TableauStudies_3.cy.ts
cypress/fixtures/ExportTableauStudies.json

- Closes SJIP-1285
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1285)
1. 
2.

feat: SJIP-1285 Adjust Cypress tests

---

.env.schema
src/components/Layout/Header/index.tsx
src/components/featureToggle/NotificationBanner/index.tsx
src/hooks/useFeatureToggle.tsx
src/views/Login/index.tsx

- Closes SJIP-1288
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1288)

feat(banner): SJIP-1288 add persistent banner

---

cypress/e2e/Consultation/PageVariant_2.cy.ts
cypress/e2e/UploadList/PageDataExploration_2.cy.ts
src/views/VariantEntity/utils/summary.tsx

- Closes SJIP-1271
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1271)

fix(variant): SJIP-1271 redirect to ensemble_gene_id

---

cypress/e2e/ManifestButton/Dataset_2.cy.ts
cypress/e2e/ManifestButton/PageStudy_1.cy.ts
cypress/e2e/Requetes/ValidationParticipants.cy.ts

- Closes SKFP-1292
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1292)
1. 
2.

feat: SJIP-1292 Adjust Cypress tests related to last ETL run

---

package-lock.json
package.json
src/graphql/constants.ts
src/locales/en.ts
src/services/analytics.ts
src/services/api/arranger/index.ts
src/store/venn/thunks.ts
src/store/venn/types.ts
src/views/Analytics/SetOperations/NoSet.tsx
src/views/Analytics/SetOperations/SelectSets.tsx
src/views/Analytics/SetOperations/index.module.css
src/views/Analytics/SetOperations/index.tsx
src/views/Analytics/SetOperations/utils.tsx
src/views/DataExploration/components/PageContent/index.tsx

[SJIP-1254](https://d3b.atlassian.net/browse/SJIP-1254)
- Add Set Operations
- add set operation flow to display venn diagram for sets
NA
https://github.com/user-attachments/assets/fa2451cf-80ac-4b11-b243-8618de3e93fe
https://github.com/user-attachments/assets/0a901ad0-001f-4784-975f-df52097bc986
https://github.com/user-attachments/assets/9af07abd-3782-40f8-8bac-d3ad8fbaf35e
https://github.com/user-attachments/assets/1887baa1-3fb8-476d-8b2b-152117cf7a1c

feat(analytics): SJIP-1254 add set operations

---

src/views/Login/TopBanner/index.module.css
src/views/Login/TopBanner/index.tsx

- Closes SJIP-1293
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1293)

feat(landing): SJIP-1293 add language selector in landing page

---

src/views/StudyEntity/index.tsx
src/views/StudyEntity/utils/file.tsx

- Closes [SJIP-1315](https://d3b.atlassian.net/browse/SJIP-1315)
We have an inconsistency in File section in the study entity.
- Manage file section display with data type and experimental strategy data.

feat(study): SJIP-1315 hide file section if no tables data

---

src/views/DataExploration/components/PageContent/tabs/Summary/ParticipantsByAge/index.tsx

- Closes SJIP-1314
Set empty state for age at first patient engagement
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1314)

fix(summary): SJIP-1314 fix loading state for participant by age

---

package-lock.json
package.json
src/locales/en.ts
src/locales/es.ts
src/utils/translation.ts

- Closes SJIP-1334
Le tooltip devrait être: Select 2 or 3 queries to generate a Venn diagram comparison
Le tooltip devrait être: Only available with 2 or 3 queries selected
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SJIP-1334)

fix(query): SJIP-1334 fix tooltips for compare button

---

package-lock.json
src/views/Analytics/SetOperations/index.module.css
src/views/Analytics/SetOperations/index.tsx

[SJIP-1317](https://ferlab-crsj.atlassian.net/browse/SJIP-1317)
[SJIP-1332](https://ferlab-crsj.atlassian.net/browse/SJIP-1332)
[SJIP-1333](https://ferlab-crsj.atlassian.net/browse/SJIP-1333)
Various fixes in venn chart with filters.
- SJIP-1317 venn chart style and change acronyms by S instead of Q
- SJIP-1332 manage disabled for reset button
- SJIP-1333 update table icon on compare and not on entity change
NA
https://github.com/user-attachments/assets/20e05c7f-6649-4182-8984-90bca9ee1214

feat(setoperation): SJIP-1332 SJIP-1317 SJIP-1333 various fixes in venn with filters

---

package-lock.json
package.json
src/views/Analytics/SetOperations/index.tsx

[SJIP-1339](https://d3b.atlassian.net/browse/SJIP-1339)
Venn chart responsive
Make venn chart responsive

fix(venn): SJIP-1339 responsive chart

---

cypress/e2e/Requetes/ValidationParticipants.cy.ts
cypress/e2e/Telechargement/ClinicalDataPageParticipant_1.cy.ts
cypress/e2e/Telechargement/ClinicalDataPageParticipant_2.cy.ts
cypress/e2e/Telechargement/ClinicalDataTableauParticipants_1.cy.ts
cypress/e2e/Telechargement/ClinicalDataTableauParticipants_2.cy.ts

- Closes SJIP-1352
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1352)
1. 
2.

feat: SJIP-1352 Adjust Cypress tests related to recent changes

---

src/index.js

- Closes SJIP-1355
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1355)

fix(sentry): SJIP-1355 ignore non-error sentry message

---

package-lock.json
package.json

Si on sélectionne un set et qu’on compare d’autres données, le set sélectionné reste actif. Le coches devraient se réinitialiser au changement de données.
- [JIRA](https://ferlab-crsj.atlassian.net/browse/)
https://github.com/user-attachments/assets/52852394-3774-4d05-b4da-6c330b6663df

fix(venn): SJIP-1356 reset select table set when venn chart is reloaded

---

src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx

- Closes SJIP-1136
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1136)

fix(demography): SJIP-1136 adjust preview svg margin

---

src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx

- Closes SJIP-1363
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1363)

fix(chart): SJIP-1363 add custom legends with patterns

---

src/views/DataExploration/components/PageContent/tabs/Summary/ParticipantsByAge/index.tsx

- Closes SJIP-1364
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1364)

feat(chart): SJIP-1364 add custom legend

---

src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx

- Closes SJIP-1345
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1345)
1. 
2.

fix(chart): SJIP-1345 change sorting for sample_type chart

---

src/locales/en.ts
src/locales/es.ts

[SJIP-1177](https://d3b.atlassian.net/browse/SJIP-1177)
Update dataset name
- Update dataset name in select and modal
[SJIP-1177]: https://d3b.atlassian.net/browse/SJIP-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analysis): SJIP-1177 fix dataset name

---

package-lock.json
package.json
src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentDiagnosisGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentPhenotypesGraphCard/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/ParticipantsByAge/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx
src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx

[SJIP-1379](https://ferlab-crsj.atlassian.net/browse/SJIP-1379)
Improve TSV download
- format frequency
- rename first column header
- remove empty column
[SJIP-1379]: https://d3b.atlassian.net/browse/SJIP-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(graph): SJIP-1379 improve download data in study and summary

---

cypress/e2e/Consultation/TableauStudies_1.cy.ts
src/views/Studies/components/PageContent/index.tsx

[SJIP-1386](https://d3b.atlassian.net/browse/SJIP-1386)
Add total files
Display total files count in the studies footer table
[SJIP-1386]: https://d3b.atlassian.net/browse/SJIP-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(studies): SJIP-1386 add total files

---

cypress/e2e/Requetes/ValidationParticipants.cy.ts

- Closes SJIP-1387
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1387)
1. 
2.

feat: SJIP-1387 Adjust Cypress tests related to last ETL run

---

package-lock.json
package.json

- Closes SJIP-1397
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1397)
1. 
2.

feat: SJIP-1397 Update testqualitycli

---

src/components/PublicLayout/Header/index.tsx

[SJIP-1408](https://d3b.atlassian.net/browse/SJIP-1408)
Update header to back to studies page
Be able to go back to public studies page.
No back link and button always focus on public study page.
https://github.com/user-attachments/assets/b4bc8b91-51b4-4f74-b458-b54fe0c0c543
[SJIP-1408]: https://d3b.atlassian.net/browse/SJIP-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(publicstudy): SJIP-1408 Update header to back to studies page

---

src/graphql/participants/models.ts
src/graphql/participants/queries.ts
src/graphql/quickFilter/queries.ts
src/locales/en.ts
src/locales/es.ts
src/utils/translation.ts
src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
src/views/DataExploration/index.tsx

[SJIP-1418](https://d3b.atlassian.net/browse/SJIP-1418)
Add maxo facet and column
- Add facet on maxo.code
- Add column with see more behavior and display maxo.display and maxo.code with link
NA
[SJIP-1418]: https://d3b.atlassian.net/browse/SJIP-1418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(participants): SJIP-1418 add maxo column and facet

---

NEWS.md

- Closes SJIP-000
- [JIRA](https://d3b.atlassian.net/browse/SJIP-000)
1. 
2.

fix: SJIP-000 format news correctly

---

cypress/e2e/Consultation/Landing.cy.ts
src/locales/en.json
src/locales/es.json
src/locales/fr.ts

https://d3b.atlassian.net/browse/SJIP-1422

feat: sjip-1422 add policies and fix types def

---

src/utils/dataFiles.ts

[SJIP-1452](https://d3b.atlassian.net/browse/SJIP-1452)
Error 500 on file entity load if user is connected to authorized studies.
Load correctly file entity
[SJIP-1452]: https://d3b.atlassian.net/browse/SJIP-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(file): SJIP-1452 remove read only file access

---

src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx

[SJIP-1451](https://d3b.atlassian.net/browse/SJIP-1451)
Deduplicate diagnosis mondo column
- remove duplicates
- remove null value
[SJIP-1451]: https://d3b.atlassian.net/browse/SJIP-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(participants): SJIP-1451 remove diagnosis mondo duplicates

---

cypress/e2e/Consultation/PageParticipant_2.cy.ts
cypress/e2e/Consultation/TableauBiospecimens_3.cy.ts
cypress/e2e/Consultation/TableauFiles_3.cy.ts
cypress/e2e/Facettes/PageDataExploration_1.cy.ts
cypress/e2e/Facettes/PageDataExploration_3.cy.ts
cypress/e2e/Requetes/ValidationParticipants.cy.ts

- Closes SJIP-1460
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1460)
1. 
2.

feat: SJIP-1460 Adjust Cypress tests related to recent changes

---

src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx

- [SJIP-1461](https://d3b.atlassian.net/browse/SJIP-1461)
- [SJIP-1463](https://d3b.atlassian.net/browse/SJIP-1463)
- Files tab is in error with woof woof study
- Sort on files tab generate error
- Files tab is displayed and sort is working
https://github.com/user-attachments/assets/ab81af5b-a14a-4f16-9761-7fed275300f2
https://github.com/user-attachments/assets/cd3c01d4-cab0-43a7-af25-be951def8b6a
[SJIP-1461]: https://d3b.atlassian.net/browse/SJIP-1461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SJIP-1463]: https://d3b.atlassian.net/browse/SJIP-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(files): SJIP-1461 add check on access urls
